### ISSUE TITLE
2023-11-22-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#15]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by Paul2021-R** [comment]
# 금일 작업

- [ ] 알람 모듈 설계 마무리 
- [ ] 인수인계 상황 점검 & 파악하기(백, 프론트)
- [ ] 회식 예약 준비
- [ ] 구현 필요 내용 학습 보완

---
# 금주 작업 

- [ ] 제이위님 제공 질문 내용 검토하기 
- [ ] 세부기획 보완 하기

**Comment by hyeon81** [comment]
- [ ] pr 확인
- [ ] ssr 시 토큰 담아서 보내는 부분 확인
- [ ] 목표기간 슬라이더 작업
- [ ] 폼 제출시 validation 확인
- [ ] 폼 모달을 페이지로 바꾸기
- [ ] 모집글 높이 고정.
- [ ] 세부옵션 필터링 확인
- [ ] 디자인 확인 후 빠진 요소 추가

**Comment by juhyeonlee134** [comment]
- [ ] NHN cloud 오브젝트 스토리지 적용
- [ ] Git wiki 문서 최신화

**Comment by wochae** [comment]
- [ ] 알림 요청 DTO 결정
- [ ] API 만들기 (뷰, 로컬, 테스트)

**Comment by SaltySalt77** [comment]
#### 운영진
- [ ] 디엠 돌리기

#### 개발진
- [ ] 밀린 pr 리뷰
- [ ] 어제 올린 풀 리퀘스트 코멘트 더 달아두기 (의도하지 않았으나 너무 커짐)
- [ ] 인수인계 문서 정리

**Comment by KRimwoo** [comment]
- [ ] 개인정보 받아오는 api에 구글연동정보 추가 요청
- [ ] 공통컴포넌트 디자인 적용 시작

**Comment by yoouyeon** [comment]
- [ ] 팀 공지사항 게시판 기능 확정, api 논의
- [ ] 팀 공지사항 게시판 글쓰기, 수정기능 마무리 https://github.com/peer-42seoul/Peer-Frontend/issues/338#issue-2002843422
- [ ] 공지사항 위젯 구현 시작 OR 쪽지 디자인 작업 시작

**Comment by joonseong11** [comment]
- [ ] pr 확인
- [ ] 모집글쓰기 수정페이지 레이아웃 디자인 반영 마무리
- [ ] 백엔드 연동 다시 한번 체크
- [ ] 수정페이지, 인터뷰 답변 달려있는지 여부 api 추가 논의
- [ ] 논의후 인터뷰 답변 달려있으면 새로등록 막기

**Comment by perman0519** [comment]
- [ ] 파일업로드 nhn으로 변경
- [ ] 인수인계 파일 만들기

**Comment by HiHoi** [comment]
- [ ] SSR token 문제 고민
- [ ] 아이콘 관련 문서화
- [ ] PWA API 문서 작성
- [ ] 프리캐싱 기능 작업

**Comment by sinryuji** [comment]
- [ ] 유저 활동 추적 개발 끝장내버리기
