### ISSUE TITLE
2023-11-23-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#18]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
# 분류된 작업

#### jujeon 
- 개인정보동의약관
- 모집글쓰기 작성 및 수정
- 히치하이킹
- 관리자페이지
    
#### hoslim
- 팀설정페이지
- 검색
- PWA

#### hyna
- 마이페이지, 프로필, 홈페이지설정
- 피어로그

#### hujeong
- 회원가입
- 탈퇴
- 마이페이지 개인정보

#### hyeokim2
- 메인페이지, 네비게이션바, 탭바
- 모집글 뷰
- DnD

#### jeyoon
- 팀페이지 메인화면
- 쪽지
- 툭박스(위젯)

#### woorikim
- 로그인
- 비밀번호 찾기
- 쇼케이스

#### haryu
- 알림 (nest)
- 쪽지
- socket (온라인 여부 관리 등)
- Algorithm (개인성향 측정, 팀평가)

#### jwee
- 게시판
- Algorithm (개인성향 측정, 팀평가)
- 피어로그

#### hyeongki
- 사용자추적
- 고나리자
- 인공지능 입출력 (chatGPT)

#### juhyelee
- 프로필
- 회원
- 피어로그
- 업적

#### junssong
- 회원
- 팀 (팀페이지, 팀설정 등)

#### wochae
- 알람 (스프링)
- 인공지능 입출력 (chatGPT)

**Comment by yoouyeon** [comment]
- [ ] PR 확인하기
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/338 반드시 마무리 (반드시.)
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/361 시작

**Comment by SaltySalt77** [comment]
#### 운영진

- [ ] 회의 준비
- [ ] 회의 참석

#### 개발진

- [ ] light/dark 모드용 토글
- [ ] 밀린 pr 리뷰
- [ ] Typography custom variant 관련 인수인계 문서 작성

**Comment by wochae** [comment]
- [ ] 스프링 강의듣기
- [ ] 데이터베이스 학습
- [ ] 알람 모듈 살펴보기

**Comment by weejihye** [comment]
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/405
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/406
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/404
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/403
- [ ] 팀게시판 api 구현 (https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=45389546)

**Comment by hyeon81** [comment]
- [ ] pr 확인
- [ ] 어제 작업한 것 pr 올리기
- [ ] 쿠키 공부
- [ ] 모집글 높이 고정.
- [ ]  세부옵션 필터링 확인
- [ ] 디자인 확인 후 빠진 요소 추가
- [ ] 외주 작업

**Comment by juhyeonlee134** [comment]
- [ ] 쓰레드 관련 API
- [ ] 뮤텍스 락
- [ ] 컨디션 변수

**Comment by joonseong11** [comment]
- [ ] 모집글쓰기 수정페이지 레이아웃 디자인 반영 마무리
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/350
- [ ] 논의후 인터뷰 답변 달려있으면 새로등록 막기
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348

**Comment by KRimwoo** [comment]
- [ ] pr 확인
- [ ] 어제 하던 디자인 적용 작업 마무리해서 pr올리기
- [ ] 학교 프로젝트 작업
