### ISSUE TITLE
2023-11-24-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#21]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
# 분류된 작업

#### jujeon 
- 개인정보동의약관
- 모집글쓰기 작성 및 수정
- 히치하이킹
- 관리자페이지
    
#### hoslim
- 팀설정페이지
- 검색
- PWA

#### hyna
- 마이페이지, 프로필, 홈페이지설정
- 피어로그

#### hujeong
- 회원가입
- 탈퇴
- 마이페이지 개인정보

#### hyeokim2
- 메인페이지, 네비게이션바, 탭바
- 모집글 뷰
- DnD

#### jeyoon
- 팀페이지 메인화면
- 쪽지
- 툭박스(위젯)

#### woorikim
- 로그인
- 비밀번호 찾기
- 쇼케이스

#### haryu
- 알림 (nest)
- 쪽지
- socket (온라인 여부 관리 등)
- Algorithm (개인성향 측정, 팀평가)

#### jwee
- 게시판
- Algorithm (개인성향 측정, 팀평가)
- 피어로그

#### hyeongki
- 사용자추적
- 고나리자
- 인공지능 입출력 (chatGPT)

#### juhyelee
- 프로필
- 회원
- 피어로그
- 업적

#### junssong
- 회원
- 팀 (팀페이지, 팀설정 등)

#### wochae
- 알람 (스프링)
- 인공지능 입출력 (chatGPT)

**Comment by yoouyeon** [comment]
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/361
- [ ] 쪽지 페이지 디자인 작업 시작

**Comment by Paul2021-R** [comment]
- [ ] 인수인계 과정 점검 
- [ ] 전체 리더스 회의 진행, 다음 진행 단계 관련하여 논의 마무리
- [ ] nestjs CICD 구축

**Comment by juhyeonlee134** [comment]
- [ ] 인수인계 문서 점검
- [ ] 그 외 오류 및 버그 수정

**Comment by SaltySalt77** [comment]
- [ ] pr 올리기
- [ ] 밀린 pr 리뷰
- [ ] 디자인 입히기 #https://github.com/peer-42seoul/Peer-Frontend/issues/363

**Comment by sinryuji** [comment]
- [ ] 모듈 설계서 작성
- [ ] ChatGPT API 맛보기

**Comment by joonseong11** [comment]
- [ ] 모집글쓰기 수정페이지 레이아웃 디자인 반영 마무리
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/350
- [ ] 논의후 인터뷰 답변 달려있으면 새로등록 막기
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348

**Comment by HiHoi** [comment]
- [ ] 인수인계 문서 정리
- [ ] 맡은 파트 문서화
- [ ] FE팀 인수인계 문서화 총관리

**Comment by hyeon81** [comment]
- [ ] pr 확인
- [ ] ssr 쿠키
- [ ] 메인/모집글 디자인 적용

**Comment by KRimwoo** [comment]
- [ ] 인수인계 문서 작성
- [ ] 작업하던 것 pr 올리기

**Comment by perman0519** [comment]
- [ ] 팀 설정 페이지 api 핫 픽스
- [ ] qa 진행
- [ ] 남은 작업 리스트 정리

**Comment by wochae** [comment]
- [ ] 디비 설계
- [ ] 엔티티 생성
- [ ] 간단한 api 만들기
