### ISSUE TITLE
2023-11-29-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#25]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|05:30|06:30|(쪽지) 프론트 요청 핫픽스| ISO 8601  방식으로 수정 완료 |
|06:30|07:00|(기획) 프로필 - 스킬 api 문서 정리 완료| ISO 8601  방식으로 수정 완료|
|07:00|08:52|jwee님 인셉션 같이 고민하기| 해결 못함 ㅠ|
|||아침 식사||
|||산책||
|||(기획) 알람 RestAPI 문서작성 마무리||
|||(기획) 테그 관련 문서화 ||
|||(기획) 개인 성향 분석 관련 질문 검토||
|||이니셜 스크럼||
|||(기획) Algorithm 모듈 설계||
|||(개발) 알람 모듈 - firebase 서버 올리기 도전||
|||엔딩 스크럼||
|||(개발) 알람 모듈 우채님과 상황 논의||

**Comment by HiHoi** [comment]
12~18 
- [] H-SC API 작성
- [] H-SC 넘기기 애니메이션 설계
- [] H-SC PC 버전 와이어프레임 작업
- [] I-TM 모바일 버전 디자인 작업
- []

**Comment by joonseong11** [comment]
1:00 ~ 9:00 작업 진행 예정

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|||pr 확인|||
|1:30|2:00|스크럼|||
|||J-TB 모집글수정 QA|모집글쓰기 수정페이지에서 답이 달려있으면 수정 불가능하게 처리|WIP|
|||J-TB 모집글쓰기 QA|모집글쓰기에서 역할 추가를 누르면 작성완료 안되는 문제|| 
|||J-TB 모집글수정 QA|이미지수정로직 변경||
|||J-TB 모집글쓰기|컴포넌트 재사용성을 고려하여 부분 수정 고민(시간 필요)||
|2:00||어드민페이지|세부기획 참조해서 대략적인 와이어프레임 작업|WIP|
|2:00||어드민페이지|신고기능 api 설계|WIP|
|6:30|7:00|스크럼|||

**Comment by KRimwoo** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|14:00|이니셜 스크럼|+pr확인 및 pr올리기|
|14:00|~|비밀번호 찾기 페이지|메일 재전송 버튼 만들기|
|||oauth 연동 에러 고치기| 형키님과 논의|
|||쇼케이스| api먼저? or 목데이터로 페이지 구성하기|
|||로그인 페이지|중복 토스트 고치기|

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|18:00| H-HICH | 히치하이킹 PC 데모 만들어두기 |
|19:00| - | H-HICH | 히치하이킹 모바일 데모 만들기 |

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
| 13:30 | 14:30 | PR 확인 | 2개 |  |
| 14:30 | - | 쪽지 목록 모바일 이어서 작업 | 스와이프 삭제 기능, 디자인 적용 |  |

**Comment by wochae** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
||| 다른 모듈에서 알림 모듈 사용|추가|

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|||OAuth|OAuth 연동 문제 해결|
|||태그|기존 태그 사용되던 곳 리팩토링|
|||어드민|어드민 페이지 API 협의|

**Comment by HiHoi** [comment]
> **시작 시간**	**종료 시간**	**제목**	**내용**	**완료**
> 13:30	14:30	PR 확인	2개	
> 14:30	-	쪽지 목록 모바일 이어서 작업	스와이프 삭제 기능, 디자인 적용

https://www.framer.com/motion/ - 여기서 Drag 한번 확인해보세요
