### ISSUE TITLE
2023-12-05-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#29]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|07:30|08:00|아침 식사| |
|08:30||오전 학습| |
|11:00||갈 준비| |
|11:30||이동| |
|12:00|13:00|점심식사| |
|13:30|14:00|이니셜 스크럼| |
|||핫픽스 - message 부터 진행| |
|||핫픽스 - 기타 |작업 분배 |
|||버퍼타임| |
|||엔딩 스크럼 | |

---

### 해야할 일 정리 

- [ ] 기존 내용 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 기존 내용 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 기존 내용 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|15:00|18:00|히치하이킹 api 구현, objectService 버그픽스||

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | |:---:|:---:|:---|:---| |13:30|13:45|스크럼|이니셜 스크럼|
|13:45|14:00|어드민|어드민 페이지 API 문서화|
|14:00|~|어드민|어드민 페이지 API 개발|

**Comment by sinryuji** [comment]
- [ ] 이니셜 스크럼
- [ ] 어드민 페이지 API 문서화
- [ ] 어드민 페이지 API 개발

**Comment by yoouyeon** [comment]
- [ ] 개별 쪽지 페이지 PC 뷰 마무리하기 (점검안된 부분 마무리)
- [ ] 쪽지 목록 디자인 입히기 (PC 뷰 완성하는게 목표 👍)

**Comment by wochae** [comment]
- [ ] 알림 모듈 작업 01
- [ ] api 테스트
- [ ] 알림 문서화

**Comment by HiHoi** [comment]
13시 ~ 22시

- 쇼케이스 백엔드 연동
- 쇼케이스 PC 버전 마무리
- 디자인 단위 변경
- PWA 푸시 알림 
- PWA 프리캐싱

**Comment by hyeon81** [comment]
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/397
- [ ] 메인페이지, 모집글페이지, 네비게이션 디자인 작업

**Comment by KRimwoo** [comment]
- [ ] 이전 pr conflict수정
- [ ] 마지막 작업 pr올리기
- [ ] 마이페이지 디자인 작업

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:00|13:00|운영진|운영진 회의 |
|||H-HITCH|히치하이킹 카드 뒷면 구현 및 모바일 페이지 구현 |

이동 중일 때는 카드 뒤집는 라이브러리 찾아볼 예정입니다.
https://github.com/peer-42seoul/Peer-Frontend/issues/390
