### ISSUE TITLE
2023-12-06-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#30]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|07:30|08:00|아침 식사| |
|10:10||오전 학습|블로그에 글 정리|
|||오전 작업|쪽지 작업 시작|
|12:00|13:00|점심식사| |
|13:30|14:00|이니셜 스크럼| |
|||알람 미팅| |
|||jwee님 미팅||
|||오후 작업| 종료 로직 관련 논의 : jwee님, hoslim님 과?|
|||엔딩 스크럼 | |
---

### 해야할 일 정리 

- [ ] 기존 내용 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 기존 내용 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 기존 내용 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:00|12:30|H-HITCH| 코드 리펙토링|
|13:30| | 스크럼|이니셜 스크럼 참석
| | | 논의 | 태그 관련 논의 |
| | | H-HITCH | 카드 뒤집기 데모 |

https://github.com/peer-42seoul/Peer-Frontend/issues/390

**Comment by sinryuji** [comment]
- [ ] 이니셜 스크럼
- [ ] 모집게시글 태그 리팩토링
- [ ] 신고 관련 API 구현
- [ ] 블랙리스트 관련 API 구현

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
|12:00| - | CuModal | 모달 디자인 적용 작업 마무리, 기존 코드에 적용 |  |
| - | - |  |  |  |

**Comment by HiHoi** [comment]
13~22

1. 작업페이지에 작업 코드 전부 정리: 범주부터 한번에
2. Todo 리스트 정리 이후 보기 쉽게 피그마에 작업 공간 만들 예정
3. 문서화된 결과물을 전부 컨펌
4. API 문서 전부 컨펌
5. PWA 푸시 알림 작업 진행


특이사항: 
- FE 문서 작업 이후 스텝 2 작업량에 대한 확정 및 분배도 진행될 예정
- 작업 속도 높이기 위한 디자인 팀 구축 예정: PC와 모바일 반응형 담당 팀
- 오늘 퍼스널 컬러랑 취업 컨설팅 정도만 참여할 생각이 있는데 어떻게 될지는 모르겠음 ㅠ

**Comment by wochae** [comment]
- [ ] 어제 알람 작업 마저 하기
- [ ] 챗지피티..?

**Comment by KRimwoo** [comment]
- [ ] 어제 pr수정 및 확인
- [ ] 공통 mui 컴포넌트 스타일링
- [ ] 마이페이지 인수인계보고 작업

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|14:00|15:00|showcase favorite, like 할 때 response body 추가||
