### ISSUE TITLE
2023-12-08-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#32]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by HiHoi** [comment]
13 ~ 22

1. 팀 설정 페이지에 역할 추가 및 변경 기능 추가
2. 팀 설정 페이지 리팩토링
3. 쇼케이스 PC 버전 리팩토링
4. 쇼케이스 모바일 리팩토링: 바뀐 API에 맞게끔

**Comment by joonseong11** [comment]
### 1:30 ~ 12:00 작업가능 (선릉 위워크)
## 담당 및 현황
- 개인정보약관 페이지 (모바일 반응형 디자인 삽입필요)
- 모집글 작성, 수정 페이지 (QA 진행중, 디자인 작업중)
- 어드민 페이지 (와이어프레임, api 설계 완료, 신고 - 태그 - 월렛/업적 - 유저 - 공지 - 배너 순으로 작업예정)
## QA
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/322
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|-|-|pr 확인||✅|
|-|-|ADMIN| [와이어프레임] 공지관리에 숨김 기능 추가 작업|✅|
|-|-|ADMIN| [API] 공지관리에 숨김 기능 api 논의|✅|
|-|-|ADMIN| [API 문서 검토]|✅|
|-|-|J-TB 인터뷰 응답 선형배율 오류 수정|https://github.com/peer-42seoul/Peer-Frontend/issues/317||
|-|-|J-TB 스터디명 표기 오류 수정|https://github.com/peer-42seoul/Peer-Frontend/issues/382||
|-|-|J-TB 역할 추가시 글작성불가 오류 수정|https://github.com/peer-42seoul/Peer-Frontend/issues/374||
|-|-|ADMIN|신고 관리 레이아웃 페이지 레이아웃 작업||
|-|-|A-JOI|개인정보약관 모바일 반응형 디자인 반영||

**Comment by wochae** [comment]
- [ ] 이니셜 스크럼
- [ ] K-PWA API 구현하기

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30||스크럼|스크럼 참석 |
|||H-HITCH| 클릭 이벤트 / 드래그 이벤트 분리 처리 |
|||운영진|긴급회의|

// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~

**Comment by joonseong11** [comment]
42경산 rush01
