### ISSUE TITLE
2023-12-11-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#33]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
### Time Table

| **시작 시간** | **종료 시간** |       **제목**       | **내용**                        |
|:-------------:|:-------------:|:--------------------:|:------------------------------- |
|               |               |     스레드 정리      | 활성 스레드 전체 일괄 정리 진행 |
|     08:20     |               |      아침 식사       |                                 |
|               |               |      아침 학습       | 인강 학습 진행                  |
|               |               |       집 청소        |                                 |
|               |               |      점심 식사       |                                 |
|     13:30     |     14:00     |    이니셜 스크럼     |                                 |
|               |               |    메시지 핫픽스     |                                 |
|               |               | ObjectStorage 핫픽스 |                                 |
|               |               |   기타 진행시 적음   |                                 |
|     19:30     |     20:00     |     엔딩 스크럼      |                                 |
|               |               |         운동         |                                 |

---

### 해야할 일 정리 

- [ ] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [ ] 핫픽스 ) ObjectStorage

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:00|11:30|디코|업무 연락 처리 |
|13:30|13:40|스크럼|이니셜 스크럼 참석|
|13:40|15:30| H-HITCH|현재 작업 된 부분 로직과 기존에 머지된 코드 합치기|
|15:30|  | H-HITCH | PR올리기|

- [ ] 히치하이킹 코드 정리

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:00|15:00|역할 기능 부분 정리||
|15:00|16:00|백서 원고 작성 및 제출||
|16:00|18:00|잔업||
|18:00|18:30|저녁식사||
|18:30|19:30|엔딩스크럼||
|19:30|~|잔업||

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:45|스크럼|이니셜 스크럼|
|13:45|-|어드민|어드민 페이지 블랙리스트 관련 API 개발|

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
| - | - | PR 마무리 | https://github.com/peer-42seoul/Peer-Frontend/pull/414 확인받고 머지하기,,,<br/>(발생한다면) conflict 해결하기 |  |
| - | - | 개별 쪽지 페이지 모바일뷰 디자인 | https://github.com/peer-42seoul/Peer-Frontend/issues/400 <br/> https://github.com/peer-42seoul/Peer-Frontend/issues/402 |  |

**Comment by HiHoi** [comment]
13시 ~ 22시

- 프론트엔드 작업 분배
- 쇼케이스 리팩토링
- 팀 설정 페이지의 역할 변경 추가 기능 구현

**Comment by wochae** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:00| 스크럼 | 이니셜 스크럼 |
|14:00|14:30| 클러스터 가야지 | 꼭 가야할까? |
|14:30| | 작업 | 알람 관련 |
해야할 일
- [ ] 알람모듈
- [ ] 강의수강
- [ ] 원고작성

**Comment by joonseong11** [comment]
### 13:00 ~ 22:00 작업가능 (도림천 집)
## 담당 및 현황
- 개인정보약관 페이지 (모바일 반응형 디자인 삽입필요)
- 모집글 작성, 수정 페이지 (QA 진행중, 디자인 작업중, 늦어도 수요일까지 완성목표. 화요일까지 목표였으나 42경산봉사 이유로 수요일..)
- 어드민 페이지 (와이어프레임, api 설계 완료, 신고 - 태그 - 월렛/업적 - 유저 - 공지 - 배너 순으로 작업예정)
## QA
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/322
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|-|-|pr 확인|||
|-|-|J-TB 모집글 작성시 인터뷰 모달|디자인 반영||
|-|-|J-TB 모집글 수정 페이지 QA|||
|-|-|ADMIN|신고 관리 레이아웃 페이지 레이아웃 작업||
|-|-|ADMIN|어드민 로그인 페이지 레이아웃 작업||
