### ISSUE TITLE
2023-12-12-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#34]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |       **제목**       | **내용**                        |
|:-------------:|:-------------:|:--------------------:|:------------------------------- |
|               |               |     스레드 정리      | 활성 스레드 전체 일괄 정리 진행 |
|     07:30     |     08:30     |      아침 식사       |                                 |
|     09:00     |     :     |      아침 학습       | 인강 학습 진행                  |
|               |               |      점심 식사       |                                 |
|     13:30     |     14:00     |    이니셜 스크럼     |                                 |
|               |               | message hot fix |                                 |
|               |               | 미 분배 작업 리펙토링     |                                 |
|     19:00     |     19:30     |     엔딩 스크럼      |                                 |
|               |     21:16     | ObjectSotrage 핫픽스 |                                 |
|     21:30     |     22:30     |         운동         |                                 |

---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [x] 핫픽스 ) ObjectStorage

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:45|14:00|스크럼|이니셜 스크럼|
|14:00|-|어드민|블랙리스트 API 개발|

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
| 13:00 | - | 개별 쪽지 페이지 모바일뷰 디자인 | https://github.com/peer-42seoul/Peer-Frontend/issues/400 <br/> https://github.com/peer-42seoul/Peer-Frontend/issues/402 | 진행중 |
| 17:30 | - | 저녁 약속.. |  |  |

**Comment by hyeon81** [comment]
| **시작 시간** | **종료 시간** | **내용** |
|:---:|:---:|:---|:---|
|13:00|22:00|외주작업|
|22:00|24:00|메인페이지 디자인 조금 입히고 pr 올리기|

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:50|스크럼|이니셜 스크럼 참석 |
|||C-MYPAGE|이미지 들어간 부분 모두 next/Image에서 mui로 바꾸기 |

**Comment by wochae** [comment]
- 이니셜 스크럼
- 알람 작업

**Comment by HiHoi** [comment]
13:30 ~ 22:00

- 팀 설정 페이지에서 팀 역할 추가 및 변경 기능 추가
- 쇼케이스 마무리
- 이미지 이슈 체크

**Comment by KRimwoo** [comment]
- pr 확인
- 작업 할당 받기

**Comment by joonseong11** [comment]
모집글 모달에 반응형 디자인 입히기
모집글 작성 디자인 반영 끝나면 수정페이지에 그대로 입히기
Pr 확인
모집글 수정페이지 QA 처리
어드민 로그인 페이지 로직 적용
