### ISSUE TITLE
2023-12-14-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#36]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:00||S-SC|쇼케이스 작성 페이지 api 논의|
|15:00 | |이야기|동아리 개발 관련 이야기 |
| | |S-SC |쇼케이스 작성 페이지 컴포넌트 배치 마저 하기 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~

**Comment by HiHoi** [comment]
12~18

- 에디터 테스트
- 팀 설정 페이지 기능 추가
- 프리캐싱 논의

**Comment by joonseong11** [comment]
### 10:00 ~ 02:00 작업가능 (집)

## 담당 및 현황
- 개인정보약관 페이지 (db 약관 연동 api 논의 필요)
- 모집글 작성, 수정 페이지 (QA 진행중, 디자인 작업중)
- 어드민 페이지 (와이어프레임, api 설계 완료, 로그인 - 신고 - 태그 - 월렛/업적 - 유저 - 공지 - 배너 순으로 작업예정)
## QA
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/322
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|-|-|J-TB 모집글 QA|pull request 올리기|✅|
|-|-|pr 확인|||
|-|-|J-TB 모집글 작성, 수정|에러발생시 상세 에러메시지 반영||
|-|-|J-TB 모집글 작성시 인터뷰 모달|디자인 반영||
|-|-|J-TB 모집글|모바일 디자인 반영||
|-|-|ADMIN|어드민 로그인 페이지 레이아웃 작업||

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:45|스크럼|이니셜 스크럼|
|-|-|어드민|블랙리스트 PR 올리기|
|-|-|어드민|사용자 활동 추적 리팩토링|
|-|-|어드민|월렛 관련 API 개발|

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |       **제목**       | **내용** |
|:-------------:|:-------------:|:--------------------:|:-------- |
|     13:30     |     14:00     |    이니셜 스크럼     |          |
|               |               |    신고 관련 논의    |          |
|               |               | 알람 진행 상황 파악 |          |
|               |               |    message main service 수정      |     |
|               |               |   message bug 수정    |          |
|     19:00     |     19:30     |     엔딩 스크럼      |          |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [ ] 핫픽스 ) ObjectStorage

**Comment by wochae** [comment]
- 이니셜스크럼
- 알람 기획하기
- 스프링 강의

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:00|12:20|쇼케이스 api 논의||
|13:30|14:00|이니셜 스크럼||
|14:00|14:30|엔티티 변경된 부분과 코드 컨펌|haryu|
|14:30|17:00|쇼케이스 뷰페이지, 댓글, 작성기능 구현||
|17:00|~|외부작업||
