### ISSUE TITLE
2023-12-15-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#37]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |         **제목**          | **내용**                              |
|:-------------:|:-------------:|:-------------------------:|:------------------------------------- |
|     09:00     |     09:30     |         아침 식사         |                                       |
|               |     11:30     |         나갈 준비         |                                       |
|               |               |           이동            | 클러스터로...                         |
|               |               |         점심 식사         |                                       |
|     13:30     |     14:00     |       이니셜 스크럼       |                                       |
|               |               |      신고 관련 논의       | 어제 못한거 & 알람 관련 정리          |
|               |               |    알람 진행 상황 파악    | 진행 사항 파악 및 추가 논의(어드민쪽) |
|               |               |   오전 학습 미진행 분량   | 약속한 만큼 진행 예정                 | 
|               |               | message main service 수정 |                                       |
|               |               |     message bug 수정      |                                       |
|     19:00     |     19:30     |        엔딩 스크럼        |                                       |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [ ] 핫픽스 ) ObjectStorage

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:50|스크럼|이니셜 스크럼 |
|14:00|14:30|미팅|그린님과 미팅|
|15:00||회의|피어 리더스 회의|
|||S-SC|쇼케이스 작성 폼 pr 올리기|
|||S-SC|쇼케이스 링크 인풋 만들기|

**Comment by HiHoi** [comment]
13 ~ 22

- 팀활동완료페이지 와이어프레임
- 운영팀과 미팅
- 개발백서 작성
- sonar cloud 검토 후 적용

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:45|스크럼|이니셜 스크럼|
|13:45|-|어드민|월렛 관련 API 개발|

**Comment by wochae** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|14:00|이니셜 스크럼| |
|14:00|15:00|알람 api|  |
|15:00|16:00|코드 리뷰| |
|16:30|18:00|엔딩 스크럼| |

**Comment by joonseong11** [comment]
### 10:00 ~ 02:00 작업가능 (집)

## 담당 및 현황
- 개인정보약관 페이지 (db 약관 연동 api 논의 필요)
- 모집글 작성, 수정 페이지 (QA 진행중, 디자인 작업중)
- 어드민 페이지 (와이어프레임, api 설계 완료, 로그인 - 신고 - 태그 - 월렛/업적 - 유저 - 공지 - 배너 순으로 작업예정)
## 추후 작업
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348
- [ ] 이미지 업로드시 자동으로 용량 줄이기
- [ ] 글쓴이가 아닐때 edit으로 url 직접 치고 들어오는경우 막기

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|-|-|pr 확인|||
|3:00|-|피어 리더스 미팅|||
|-|-|어드민|신고하기에 유저, 팀 관련 논의||
|-|-|J-TB 모집글 작성, 수정|에러발생시 상세 에러메시지 표시||
|-|-|J-TB 모집글 작성, 수정|인터뷰 모달 디자인 반영||
|-|-|J-TB 모집글 작성, 수정|모바일 디자인 반영||
|-|-|ADMIN|어드민 로그인 페이지 레이아웃 작업||
