### ISSUE TITLE
2023-12-18-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#38]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |       **제목**       | **내용**                  |
|:-------------:|:-------------:|:--------------------:|:------------------------- |
|               |     08:40     |    휴식 & 집 정리    |                           |
|     08:40     |     09:00     |      할일 정리       |                           |
|               |               |      오전 학습       |                           |
|               |               | 코드리뷰 & 내용 확인 |                           |
|     13:30     |               |    이니셜 스크럼     |                           |
|               |               |    코드 스멜 수정    |                           |
|               |               | 버그 픽스 작업 수정  |                           |
|               |               |     NestJS CI/CD     |                           |
|               |               |       리더회의       | 정리 내용을 기반으로 공지 |
|     18:00     |               |     엔딩 스크럼      |                           |
|               |               |      저녁 운동       |                           |
|               |               |      추가 작업                |           |                |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [x] 핫픽스 ) ObjectStorage

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
| 12:00 | - | 밀린 PR 리뷰 | - https://github.com/peer-42seoul/Peer-Frontend/pull/416 <br/> - https://github.com/peer-42seoul/Peer-Frontend/pull/430 <br/> - https://github.com/peer-42seoul/Peer-Frontend/pull/431 <br /> - https://github.com/peer-42seoul/Peer-Frontend/pull/433 |  |
| - | - | 쪽지 목록 페이지 | 모바일 뷰 디자인 |  |

**Comment by HiHoi** [comment]
12~19

- [ ] 코드 스멜 고치기: 100개 정도?
- [ ] 팀 완료 페이지
- [ ] 팀 설정 페이지
- [ ] 리더 회의

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30||회의|리더스 회의 |
| | | H-HITCH | 히치하이킹 뒷면 데이터 가져오기|
| | | H-HITCH | 히치하이킹 뒷면 구현|
| | | H-HITCH | 히치하이킹 카드 되돌리기 기능|

히치하이킹 관련 code smells 고치기

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|12:00|13:00|꼬인 git 풀기|도움필요|
|13:00|14:00|클러스터로 이동||
|14:00|15:30|맥북 반납||
|15:30|17:00|집으로 이동||
|17:00|~|핫픽스 및 히치하이킹||

**Comment by joonseong11** [comment]
### 1:00~10:00

## 담당 및 현황
- 개인정보약관 페이지 (db 약관 연동 api 논의 필요)
- 모집글 작성, 수정 페이지 (QA 진행중, 디자인 작업중)
- 어드민 페이지 (와이어프레임, api 설계 완료, 로그인 - 신고 - 태그 - 공지 - 배너 - 월렛/업적 - 유저 순으로 작업예정)

## 추후 작업
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/348
- [ ] 이미지 업로드시 자동으로 용량 줄이기
- [ ] 글쓴이가 아닐때 edit으로 url 직접 치고 들어오는경우 막기
- [ ] 에디터 컴포넌트 적용
- [ ] 변경된 역할, 인원부분 반영

|**시작 시간** | **종료 시간** | **제목** | **내용** | **완료 여부** |
|:---:|:---:|:---|:---|:---| 
|-|-|pr 확인|||
|-|-|J-TB 모집글 작성, 수정|인터뷰 모달 디자인 반영||
|-|-|J-TB 모집글 작성, 수정|모바일 디자인 반영||
|-|-|J-TB 모집글 작성, 수정 QA||

**Comment by wochae** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|10:00|11:00|개발백서 작성|  |
|11:00|12:00|| 점심 |
|13:30|15:00| 이니셜과 작업 |  |
|15:00|15:30| 병원 |  |
|17:00|18:00| 작업과 엔딩 |  |
|18:00|19:00|| 저녁 |

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:45|스크럼|이니셜 스크럼|
|13:45|14:00|어드민|어드민 공지사항 API 개발|
