### ISSUE TITLE
2023-12-19-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#39]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:30|12:00|회의|운영진 리더스 회의 |
|14:00| | 회의 |전체 회의|
| | | H-HITCH | 드롭다운 메뉴 누르면 카드 뒤집히는 현상 해결|
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |    **제목**    | **내용** |
|:-------------:|:-------------:|:--------------:|:-------- |
|               |               | 자유 정리 시간 |          |
|               |               |      이동      |          |
|     14:00     |               | 이니셜 스크럼  |          |
|               |               |  개발 후속 조치 준비   |          |
|               |               |                |          |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [ ] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [ ] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [x] 핫픽스 ) ObjectStorage

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
| 14:00 | - | 이니셜스크럼 + a |  |  |
| - | - | 팀 공지사항 게시판 | 디자인 |  |

**Comment by KRimwoo** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |**완료**|
|:---:|:---:|:---|:---|
|14:00|14:30|이니셜 스크럼|||
|14:30|~|상대방프로필보기|api 논의 필요?||

**Comment by HiHoi** [comment]
14~22

- PWA 알림 연동
- 팀 설정 페이지 디자인
- 활동 완료 페이지 디자인
- 코드 스멜 부분 체크

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|14:00|14:30|스크럼|이니셜 스크럼|
|14:30|-|공지사항|공지사항 리스트|
|-|-|공지사항|공지사항 보기|
|-|-|공지사항|공지사항 삭제|
|-|-|공지사항|공지사항 수정|

**Comment by hyeon81** [comment]
* 이니셜스크럼
* dnd 레이아웃 오류 수정(얼마나있을지 모름) dnd api 논의
-> https://github.com/peer-42seoul/Peer-Frontend/issues/335
* 메인페이지, 모집글 뷰, 모집글 폼페이지 자잘한 기능들 수정 
-> https://github.com/peer-42seoul/Peer-Frontend/issues/397
-> https://github.com/peer-42seoul/Peer-Frontend/issues/408

**Comment by joonseong11** [comment]
- [ ] 모집글 작성, 글쓴이의 자기 역할 선택 추가
- [ ] 모집글 수정, 역할부분 아예 빼기로
- [ ] 모집글 수정시 이미지 받아와지는지 테스트 (백엔드 머지필요)
- [ ] 모집글 수정시, 작성완료 테스트 (백엔드 머지필요)
- [ ] 모집글에서 태그 테스트 (백엔드 머지필요)
- [ ] 모집글 작성 수정시, 총인원 부분 변경된 api 반영 (필드명 max)
- [ ] 모집글쓰기 에러 케이스 알림 내역 띄워주기 추가
