### ISSUE TITLE
2023-12-20-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#40]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |        **제목**        | **내용**  |
|:-------------:|:-------------:|:----------------------:|:--------- |
|     6:00      |     6:50      | 주혜리 필로소퍼 도와줌 |           |
|     6:50      |     7:40      |     하루 일정 정리     |           |
|               |               |          휴식          |           |
|               |               |   오전 청소 및 정리    |           |
|               |               |       아침 식사        |           |
|               |               |       오전 학습        |           |
|               |               |       점심 식사        |           |
|     13:30     |               |     이니셜 스크럼      |           |
|               |               |   개발 작업 / 글쓰기   | 알람 점검 |
|               |               |        저녁식사        |           |
|     18:30     |               |      엔딩 스크럼       |           |
|               |               |   엔딩 후 보충 작업    |           |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [X] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [x] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [x] 핫픽스 ) ObjectStorage

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:50|스크럼|이니셜 스크럼 |
|14:00| |C-MYPAGE|마이페이지 레이아웃 디자인|
| | | C-MYPAGE| 마이페이지 프로필 수정 버그 픽스 |
| | | H-HITCH| 토글 처리|

https://github.com/peer-42seoul/Peer-Frontend/issues/436

**Comment by HiHoi** [comment]
13:30~22:00

- [ ] 팀설정 페이지 기능 추가
- [ ] UX/UI 가이드 갈무리
- [ ] 활동 완료 페이지 작업

**Comment by joonseong11** [comment]
- 모집글 바뀐 역할부분 api 에 맞춰 작업 (글쓴이 자기 역할, 모집글 수정시에는 역할 빠짐)
- 모집글 수정, 이미지 백에서 받아와지면 이미지 수정시에만 다시 보내주는 것 반영
- 총인원 바뀐 api 에 맞춰 반영예정
- 에러케이스 세부 내역 알림

**Comment by KRimwoo** [comment]
- [ ] 텍스트, 이미지 DnD위젯 테스트

**Comment by yoouyeon** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** | **완료** |
|:---:|:---:|:---|:---| :---| 
| 11:00 | - | 마이페이지, 팀페이지 사이드바 | 디자인 적용 마무리하기 <br/> https://github.com/peer-42seoul/Peer-Frontend/issues/438 |  |
| - | - | 디자인 버그 수정 | 모집글 버튼 zIndex 문제 수정 <br/> https://github.com/peer-42seoul/Peer-Frontend/issues/418 |  |
| - | - | 캘린더 위젯 | 위젯 형태 구현 |  |

**Comment by wochae** [comment]
클러스터

- [ ] 알람 디비 문제 고치기
- [ ] 알람 조회
