### ISSUE TITLE
2023-12-21-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#41]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by sinryuji** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|-|-|어드민|어드민 배너 관련 API 개발|

**Comment by HiHoi** [comment]
14~22
- [ ] 알림 연동
- [ ] 완료 프로세스 제작

**Comment by joonseong11** [comment]
- [ ] pr 확인
- [ ] 모집글 바뀐 역할부분 api 에 맞춰 작업 (글쓴이 자기 역할, 모집글 수정시에는 역할 빠짐)
- [ ] 모집글 수정, 이미지 백에서 받아와지면 이미지 수정시에만 다시 보내주는 것 반영
- [ ] 모집글 총인원 바뀐 api 에 맞춰 반영예정
- [ ] 모집글 에러케이스 세부 내역 알림

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |       **제목**        | **내용** |
|:-------------:|:-------------:|:---------------------:|:-------- |
|     14:32     |               |  알람 모듈 인수인계   |          |
|               |               | jwee-wochae 작업 정리 |          |
|               |               |   버퍼 타임    |           |
|     18:00     |               |      엔딩 스크럼      |          |
|               |               |         귀가          |          |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [X] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [x] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 PWA 실장 : 기능 구현 - API 논의 - 작업 진행
- [ ] 2스텝 ) 스킬 기능 구현
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [ ] 버그 ) 프로필 자기 소개글 문제 이슈
- [ ] DnD) 문서화, API 제작
- [x] 핫픽스 ) ObjectStorage

**Comment by wochae** [comment]
-  알람 관련 인수 
-  팀 관련 인계

**Comment by weejihye** [comment]
* 우채님과 업무 나누기
* 핫픽스
* 히치하이킹
