### ISSUE TITLE
2023-12-22-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#42]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by sinryuji** [comment]
- [ ] 배너 보기 API 구현
- [ ] 배너 삭제 API 구현
- [ ] 배너 수정 API 구현
- [ ] 배너 게재 API 구현
- [ ] 배너 종료 API 구현

**Comment by joonseong11** [comment]
- [ ] 모집글 qa 해결 pr 올리기
- [ ] 모집글 디자인 적용
- [ ] 개발백서
- [ ] 외주 팀 프로젝트 계약서 검토
- [ ] 외주 팀 내부 미팅 준비

**Comment by Paul2021-R** [comment]
## Todo List

### Time Table

| **시작 시간** | **종료 시간** |           **제목**            | **내용** |
|:-------------:|:-------------:|:-----------------------------:|:-------- |
|     13:30     |               |         이니셜 스크럼         |          |
|     14:00     |               |    1장 기획 글 작업 마무리    |          |
|               |               |            집안일             |          |
|               |               | DnD 위젯API 및 관련 문서 작업 |          |
|               |               |           저녁 식사           |          |
|     18:30     |               |          엔딩 스크럼          |          |
|               |               |        공지 사항 작성         |          |
|               |               |                               |          |


---

### 해야할 일 정리 

- [x] 핫픽스) message controller 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/446
- [X] 핫픽스) message main service 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues/454
- [x] 핫픽스) 미 분배 작업 - 작업 분배 및 리펙토링 
  -  https://github.com/peer-42seoul/Peer-Backend/issues
- [ ] 2스텝 ) 관심 리스트 관련 수정
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=40550970
- [ ] 2스텝 ) 알람 스프링  모듈 구현 
- [ ] 2스탭 ) 알람 nest 모듈 구현 
  - https://github.com/orgs/peer-42seoul/projects/35/views/1?filterQuery=assignee%3A%22Paul2021-R%22&pane=issue&itemId=45884790 
- [ ] 2스텝 ) DnD team 용으로 수정 리펙토링
- [ ] 2스텝 ) team 종료 로직 구현 
- [ ] 2스텝 ) 회원가입 탈퇴 기능 추가 구현
- [ ] 버그 ) 프로필 자기 소개글 문제 이슈
- [ ] DnD) 문서화, API 제작
- [x] 핫픽스 ) ObjectStorage
- [ ] 다음주 해야할 작업
	- [ ] 온프로미스로 테스트 서버 이동
	- [ ] 하드웨어 메인 서버 구축, CICD 준비
	- [ ] 디자이너, 레퍼런스 미팅 필요
	- [ ] gh-pages -d public -b gh-pages

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|13:50|스크럼|스크럼 참석 |
|14:00| |병원| 병원 진료|
| | | H-HITCH| 히치하이킹 버튼으로 넘기는 기능|
| | | H-HITCH| 히치하이킹 토글 기능| 

- [ ] pr 확인

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|14:00|14:30|히치하이킹 관련 논의|hoslim, hyna, jwee|
|14:30|15:30|히치하이킹 api 구현|오늘중으로 마무리|
|15:30|16:30|역할 관련 api 구현||
|16:30|17:00|핫픽스 및 validation 체크||

**Comment by wochae** [comment]
- [ ] 팀 게시판 : 공시사항 게시판 인수받기
- [ ] 기획서. 기능명세서 읽고 관련 모듈 살펴보기
