### ISSUE TITLE
2024-01-02-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#49]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**       | **내용**                                        |
|:------------:|:------------:| -------------- | ----------------------------------------------- |
|    07:30     |              | 아침 식사      |                                                 |
|              |              | 씻기 & 정리    |                                                 |
|              |              | 오전 학습      |                                                 |
|              |              | 리더모임       |                                                 |
|              |              | 개포 이동      |                                                 |
| 13:30             |              | 전체 피어 모임 | 이니셜 스크럼 & 전체 회의 & 런칭 준비 논의 등   |
|              |              | 레퍼런스 모임  | 개발백서 관련 상황 정리 & 일정 정리 & 기능 정리 |
|              |              | 개발작업       |                                                 |
| 18:00             |              | 엔딩스크럼               |                                                 |

## ToDo List
- [ ] DnD 작업물 테스팅 작업 진행 - 필요시 픽스 
- [ ] 10:00 | 리더 모임
- [ ] 13:30 | 전체 피어 모임
- [ ] 14:30 | 레퍼런스 모임

## Issue - peer 
- [ ] 관심 리스트 페이지 접속 시 500 에러 
- [ ] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현 
- [ ] team 종료 로직 구현 
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현

## 취업 준비
- [ ] 인강 듣기 : 개발자 영어
- [ ] 인강 듣기 : 쉽게 배우는 자바 입문 과정
- [ ] 인강 듣기 : 자바 ORM 표준 JPA 프로그래밍 - 기본편 
- [ ] 취업 준비 : 코테 매일 준비

**Comment by sinryuji** [comment]
- [ ] 어드민 알림 파트 이슈 작성
- [ ] 어드민 알림 파트 API 개발

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|14:00|스크럼|이니셜 스크럼 |

- [ ] 전체 회의
- [ ] 레퍼런스 회의
- [ ] 히치하이킹 PC
- [ ] 밀린 PR 리뷰

**Comment by hyeon81** [comment]
- [ ] dnd pr 컨펌 받기
- [ ] 메인페이지 / 모집글페이지 pr 컨펌 받기
- [ ] dnd  무조건 레이아웃 가장 하단의 위젯으로 배치되는 현상, 제거 버튼 과 위젯 부분이 겹친 부분을 클릭시 제거가 아닌 위젯이 선택되는 현상 수정
- [ ] 모집글 지원 시 역할 보여주기 추가
- [ ] 메인페이지 / 모집글 페이지 디자인 보충

**Comment by yoouyeon** [comment]
### TODO
- [ ] 캘린더 위젯 미리보기 모달 마무리
- [ ] 캘린더 위젯 등록/편집 모달 마무리
### 남은 할일
- 캘린더 위젯 디자인 적용 마무리
- 캘린더 api 테스트
- 팀 공지사항 디자인
- 팀 게시판 api 논의 및 기능 구현
- 팀 게시판 디자인
- 팀 게시판 / 공지사항 위젯 구현

**Comment by KRimwoo** [comment]
- [ ] 팀페이지 텍스트 위젯 (api 제외 디자인까지)
- [ ] 팀페이지 이미지 위젯 (api 제외 디자인까지)

**Comment by HiHoi** [comment]
13~22

1. 전체 회의
2. 레퍼런스 회의
3. PWA 진행 사항 동기화
4. 팀 설정 페이지 백엔드 연동

**Comment by wochae** [comment]
- [ ] 테스트 서버 ci_cd

**Comment by joonseong11** [comment]
- [ ] 어드민 로그인 페이지 기능 구현
