### ISSUE TITLE
2024-01-03-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#50]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 12:00 |  | 나갈 준비 |  |
| 13:30 | 14:00 | 이니셜 스크럼 |  |
|  |  | 개인 일 처리  |  |
|  |  | 작업 진행 |  |
|  |  | 저녁 식사 |  |
| 18:30 | 19:00 | 엔딩 스크럼 |  |
|  |  | 보충 |  |

## ToDo List
- [ ] 올린 PR 마무리 짓기
- [ ] 버그 계열 먼저 작업 진행하기 
- [ ] 알림 스프링 모듈 파트 진행하기
- [ ] 글 퇴고 1회 진행하기 
## Issue - peer 
- [x] 관심 리스트 페이지 접속 시 500 에러 
- [ ] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현 
- [ ] team 종료 로직 구현 
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현
- [x] DnD Read Api  수정 : 204 수정(why? 아예 없을 때 새로 만들어야 하니까.);
- [ ] 소켓 활용한 사용자 판단 event 제작 필요
- [ ] 작성 글 퇴고
- [ ] 사진 준비

**Comment by HiHoi** [comment]
14~22

1. 팀 역할 백엔드 연동 작업
2. 팀 설정 페이지 고장난 부분 수정
3. 알림 탭 디자인 작업
4. 기타 개발백서 중 ux ui 작업 진행

**Comment by sinryuji** [comment]
- [x] 어드민 알림 파트 이슈 작성
### 어드민 알림 파트
- [x] 유저 기본 정보 리스트
- [x] 닉네임으로 유저 기본 정보 검색
- [x] 팀 기본 정보 리스트
- [x] 팀 명 or 팀장 닉네임으로 팀 기본 정보 검색
- [ ] 알림 보내기
- [ ] 예약 알림 리스트
- [ ] 예약 알림 가져오기
- [ ] 예약 알림 수정하기
- [ ] 예약 알림 삭제하기

**Comment by yoouyeon** [comment]
### TODO

- [ ] 모바일 캘린더 미리보기 모달 마무리
- [ ] 팀 공지사항 페이지 toast에디터, 뷰어 적용
- [ ] 팀 공지사항 페이지 디자인 적용 ( + 게시판)

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리
- 캘린더 api 테스트
- 팀 공지사항 디자인
- 팀 게시판 api 논의 및 기능 구현
- 팀 게시판 디자인
- 팀 게시판 / 공지사항 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|14:00|스크럼|이니셜 스크럼 참석 |
| 14:00| | H-HITCH|히치하이킹 카드 디자인 처리|
| | | | H-HITCH | 히치하이킹 PC 처리|

- [ ] 프로필 소개 버그 수정
- [ ] web share api 처리

**Comment by joonseong11** [comment]
피어
- [ ] pr 확인 (1h?)
- [ ] 어드민페이지 로그인 (4h?)
- [ ] 어드민페이지 공지 (4h?)
외주
- [ ] 외주계약서 초안작성 (4h)
- [ ] 추가 기능 검토 (며 칠 소요)

**Comment by wochae** [comment]
- [ ] pr 확인
- [ ] 도커 세팅 완료
