### ISSUE TITLE
2024-01-04-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#51]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**      | **내용**                   |
|:------------:|:------------:| ------------- | -------------------------- |
|    08:20     |    08:40     | 씻기 & 정리   |                            |
| 08:50             |    09:00     | 아침 식사     |                            |
| 09:00             |    10:30     | 오전 학습     |                            |
|    10:40     |    11:00     | 이동시간      |                            |
|    11:00     |    11:20     | 공유기 수령   |                            |
|              |              | 점심 식사     |                            |
|              |              | 정리 & 휴식   |                            |
|    ==13:00==     |    ==14:00==     | ==이니셜 스크럼== |                            |
|              |              | ==하드웨어 작업== | ==테스트 서버 공유기 재 구축== |
|              |              | ==문서화==        |                            |
|              |              | ==코드 작업==     |                            |
|              |              | ==저녁 식사==     |                            |
|    ==18:30==     |    ==19:00==     | ==엔딩 스크럼==   |                            |
|    19:00     | 20:30             | 운동 겸 산책  |                            |
|    20:30     |    22:00     | 보충 작업     |                            |
|    22:00     |              | 독서          |                            |
|    24:00     |              | 취침          |                            |

## ToDo List
- [ ] 버그 계열 먼저 작업 진행하기 
	- [ ] 소개글 쪽 진행 마무리
- [ ] 알림 스프링 모듈 파트 진행하기
- [ ] 글 퇴고 1회 진행하기 
- [ ] 공지 쓰기
## Issue - peer 
- [x] 관심 리스트 페이지 접속 시 500 에러 
- [ ] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현(우채)
- [ ] team 종료 로직 구현 
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현
- [x] DnD Read Api  수정 : 204 수정(why? 아예 없을 때 새로 만들어야 하니까.);
- [ ] 소켓 활용한 사용자 판단 event 제작 필요
- [ ] 작성 글 퇴고
- [ ] 사진 준비

**Comment by HiHoi** [comment]
12:00 ~ 21:00

## TODO

1. UX UI 가이드 문서 드라이브에 첨부: 사진을 별도도 추가해야하는 작업이 있음, 짤방의 경우 어떻게 처리할지 논의 필요
2. 팀 역할 변경 작업 진행중: jwee님과 협업 필요
3. UI 버그 수정 중
4. 지원자 리스트 수정 중

## 논의할 점

1. 지원자 리스트 기능에서 디자인 추가로 api 변경이 불가피: 지원자의 프로필 사진
2. 팀 생성 후 설정 페이지에 들어가면 그 팀의 주인이 지원자로 등록되어 있음
3. 모집글 만들 때 인터뷰 질문이 없어도 되는지, 없어도 된다면 지원자 리스트 변경 필요
4. 프로필 보기 기능 동기화

**Comment by sinryuji** [comment]
- [ ] alarm -> notice rename
- [ ] 사용자 추적 밴 추가
- [ ] 사용자 추적 신고 누계 추가

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|13:30|14:00|스크럼|이니셜 스크럼 참석 |
|14:00| |H-HITCH|web share api |
| | | C-MYPAGE | 관심리스트 디자인 |
| | | C-MYPAGE | 내 작업물 UI |

- [ ] PR 올리기
- [ ] PR 리뷰
- [ ] C-MYPAGE 프로필 소개 버그 픽스

**Comment by wochae** [comment]
- [ ] 보드 모듈 작업
- [ ] 새로운 망에서 cicd 확인하기

**Comment by joonseong11** [comment]
- 어드민 로그인
- 어드민 공지
