### ISSUE TITLE
2024-01-05-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#52]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by HiHoi** [comment]
12~21

1. 팀 역할 변경: 백엔드 상황 파악 후 기능 구현
2. 소켓 관련: 백엔드 상황 파악 후 연결 및 이벤트 체크
3. UX UI 가이드: 양식에 알맞게
4. 쇼케이스: 조회 페이지만? 하지만 문제는 쇼케이스의 데이터를 어떻게 빼올것인지 논의 필요
5. 알림탭: 디자인 작업 및 기능쪽 재구현
6. 팀 설정 페이지: API 변경사항 검토 후 수정

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**         | **내용** |
|:------------:|:------------:| ---------------- | -------- |
|    12:00     |    12:28     | 개인 일정        |          |
|              |              | 휴식 & 일정 정리 |          |
|              |              | 이니셜 스크럼    |          |
|              |              | 작업 진행        |          |
|              |              | 엔딩 스크럼                 |          |

## ToDo List
- [ ] 올린 PR 마무리 짓기
- [ ] 버그 계열 먼저 작업 진행하기 
- [ ] 알림 스프링 모듈 파트 진행하기
- [ ] 글 퇴고 1회 진행하기 
## Issue - peer 
- [x] 관심 리스트 페이지 접속 시 500 에러 
- [ ] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현 
- [ ] team 종료 로직 구현 
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현
- [x] DnD Read Api  수정 : 204 수정(why? 아예 없을 때 새로 만들어야 하니까.);
- [ ] 소켓 활용한 사용자 판단 event 제작 필요
- [ ] 작성 글 퇴고
- [ ] 사진 준비

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|14:00 | | C-MYPAGE | 관심리스트 디자인 |
| | | C-MYPAGE | 내 작업물 UI |

- [ ] PR 리뷰
- [ ] C-MYPAGE 프로필 소개 버그 픽스

**Comment by joonseong11** [comment]
- [ ] Pr 리뷰
- [ ] 어드민 로그인 secure and httponly cookie 로 엑세스 토큰 관리
- [ ] 어드민 공지 레이아웃 작업
- [ ] 어드민 배너 레이아웃 작업

**Comment by sinryuji** [comment]
- [ ] 팀 게시판 글쓰기 추적
- [ ] 팀 결성 추적
- [ ] 댓글 쓰게 추적

**Comment by wochae** [comment]
- [ ] 도커 마무리
- [ ] 보드, 팀 페이지 작업
