### ISSUE TITLE
2024-01-08-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#53]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 페이지 / 마이페이지 네비게이션바 오류 / 디자인 수정
- [ ] Toast UI Editor ref 문제 해결 (입력 값을 못 받아오는 중...)
- [ ] 팀 공지사항 게시판 디자인 마무리

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리
- 캘린더 api 테스트
- 팀 공지사항 디자인
- 팀 게시판 api 논의 및 기능 구현
- 팀 게시판 디자인
- 팀 게시판 / 공지사항 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by HiHoi** [comment]
12:30 ~ 21

1. 소켓 관련 이벤트 체크 후 연결 작업 준비
2. 팀 역할 변경 연동 중
3. 알림 작업 준비
4. UI UX 가이드 라인 사진 첨부 진행 중

**Comment by SaltySalt77** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|-|13:30|C-MYPAGE|관심리스트 그리드 처리 |
|||C-MYPAGE|디자인 처리 |
|||C-MYPAGE|내 작업물 디자인|

- [ ] PR 리뷰
- [ ] 초기 화면 모드 설정 버그 픽스
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~

**Comment by wochae** [comment]
Com4
- [ ] 디비 유저 등록 후 api 테스트
- [ ] Com4 프론트 넣어서 테스트

jwee님과 분업하기
작업 진행 백엔드 공유

**Comment by asroq1** [comment]
## TODO

[ ] Q/A 진행
[ ] 수정 가능한 버그 수정

**Comment by joonseong11** [comment]
- [ ] (외주) 추가요청기능 기능검토
- [ ] (외주) 대표님과 협의
- [ ] 어드민 공지 리스트 api 연결 
- [ ] 어드민 공지 새 글쓰기
- [ ] 어드민 공지 수정하기

**Comment by sinryuji** [comment]
- [ ] 백준 1문제 풀기
- [ ] 개발 백서 마무리
