### ISSUE TITLE
2024-01-09-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#54]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**                  | **내용**                                          |
|:------------:|:------------:| ------------------------- | ------------------------------------------------- |
|    08:30     |    09:00     | 아침 운동                 |                                                   |
|    10:00     |    10:30     | 아침 식사                 |                                                   |
|    10:30     |    10:50     | 작업 준비                 |                                                   |
|    13:30     |              | 전체 회의 & 이니셜 스크럼 |                                                   |
|              |              | 점심 식사                 |                                                   |
|              |              | 개발 작업 진행            | 알람 모듈, Nest 준비                              |
|              |              | 런칭 준비 필요 사항 정리  | 마케팅, 런칭 전 준비 사항 정리, 작업 할 것들 준비 |
|              |              | team 종료 로직 준비       | 로직 기반으로 API 작성하기                        |
|              |              | 저녁 식사                 |                                                   |
|              |              | 엔딩 스크럼               |                                                   |
|              |              | 후순위 작업들 마무리      |                                                   |
|              |              | 독서                      |                                                   |
|              |              | 종료                          |                                                   |

## ToDo List
- [x] 버그 계열 먼저 작업 진행하기 
	- [x] 소개글 쪽 진행 마무리
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [ ] controller 파악 
	- [ ] service 파악
	- [ ] 구현 정도 파악 
	- [ ] 리팩토링 개시
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [x] 글 퇴고 1회 진행하기 
- [x] 공지 쓰기
## Issue - peer 
- [x] 관심 리스트 페이지 접속 시 500 에러 
- [x] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [x] DnD Read Api  수정 : 204 수정(why? 아예 없을 때 새로 만들어야 하니까.);
- [x] 소켓 활용한 사용자 판단 event 제작 필요
- [x] 작성 글 퇴고
- [ ] 후기글 퇴고 필요
- [x] 사진 준비제출 완료

**Comment by joonseong11** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|-|-|개발 팀 전체 회의| - (안건)스크럼 방식 변경|
|-|-|개발 팀 전체 회의| - (안건)팀 개발 진행사항 파악|
|-|-|개발 팀 전체 회의| - (안건)개발백서 리마인드 공지|
|-|-|외주|견적서 재작성|
|-|-|외주|과업지시서 재작성 (약 70페이지)|
|-|-|외주|외주계약서 작성|
|-|-|외주|계약관련 서류 검토요청|
|09:00|13:00|어드민|변경된 api 로 엑세스 토큰 관리 적용|
|09:00|13:00|어드민|공지 새글쓰기, 수정 레이아웃 만들기|
|09:00|13:00|어드민|공지 새글쓰기, 수정 api 적용|

**Comment by hyeon81** [comment]
- [ ] dnd 레이아웃 다듬기
- [ ] 메인페이지 server side 데이터 로딩 실패 수정
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/459
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/467
- [ ] 모집글 인원수 추가
- [ ] 메인페이지, 모집글 디자인 보충

**Comment by HiHoi** [comment]
## TODO

1. 팀 역할 변경 / 추가 기능 버그 픽스 및 마무리
2. 쇼케이스 버그 픽스
3. 검색 지난 검색어 전체 삭제 추가
4. 소켓 이벤트 연결
5. UX UI 가이드 라인 오늘 마무리 작업

## 남은 작업

1. 알림 연동

**Comment by sinryuji** [comment]
- [ ] 어드민 로그인 Access Token 쿠키로 변경
- [ ] private-sources에서 커밋 발생 시 메인 레포 cd 돌리기
- [ ] 개발 백서 마무리

**Comment by wochae** [comment]
- [ ] com4 마무리
- [ ] 보드 모듈 작업
- [ ] 탈퇴 약관 알아보기

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 공지사항 게시판 디자인 마무리
- [ ] 일정 등록/편집/삭제 api 연결하기 (위젯 데이터 전역 상태로 관리하도록?)
- [ ] (시간이 된다면) 캘린더 위젯 편집 모달 디자인 적용하기

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리
- 캘린더 api 테스트
- 팀 공지사항 디자인
- 팀 게시판 api 논의 및 기능 구현
- 팀 게시판 디자인
- 팀 게시판 / 공지사항 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by asroq1** [comment]
### TODO
1. 쇼케이스 작성폼 - 설계하기
2. 쇼케이스 작성폼 - 토스트 UI 에디터 적용하기

### 남은 할일
- 쇼케이스 - CSS 적용하기
- 소케이스 작성폼 - API 찾아보기

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 내 작업물 완료
- [ ] custom breakpoints 오류 처리

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정
- [ ] api 문서에 수정 사항 반영

**Comment by weejihye** [comment]
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|11:00|12:00|테스트서버 crontab 인증서 갱신||
|14:00|15:00|병원||
|15:00|16:00|히치하이킹|| 
|16:00|17:00|toast editor 대응||
|17:00|20:00|버그픽스 및 호슬림님과 팀 종료프로세스 논의||
