### ISSUE TITLE
2024-01-10-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#55]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by HiHoi** [comment]
## 이슈

몸살감기 이슈 ㅠ
PR 체크는 계속 하겠습니다.

## TODO

1. 팀 설정 페이지에서 팀 변경 프로세스 변경
2. 소켓 연결
3. UX UI 가이드 라인 갈무리

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 쇼케이스 작성 페이지 인수인계 문서 작성 (어제 까먹고 못함)
- [ ] 공용 컴포넌트들 인수인계 문서 작성
- [ ] 내 작업물 완료
- [ ] custom breakpoints 오류 처리

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정
- [ ] api 문서에 수정 사항 반영

**Comment by asroq1** [comment]
### TODO
- [ ] 쇼케이스 작성 페이지 인수인계 받기
- [ ] 쇼케이스 작성폼 ToastUI 에디터 적용
- [ ] 이미지 미리보기 적용

남은 할일
 - [ ] 쇼케이스 api 논의하기

**Comment by sinryuji** [comment]
- [ ] private-resources reposioty_dispath 적용
- [ ] 개발백서 마무리

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 공지사항 게시판 모바일 뷰 (페이지 -> 모달 변경)
- [ ] 공지사항 위젯

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현
- 팀 게시판 api 논의, 연결
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 ☑️
- 팀 게시판 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by wochae** [comment]
- [ ] 서버 자원 할당 제한
- [ ] 가상 아이피 고정 할당
- [ ] 보드 모듈 작업
