### ISSUE TITLE
2024-01-11-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#56]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by sinryuji** [comment]
- [ ] 개발 백서 마무리
- [ ] 작업할게 없어요...

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 11:10 |  | 작업 준비 | 내 작업 준비, 형키님 작업 준비, test CICD 완성 여부 점검 |
| 12:00 | 13:00 | 점심 식사 |  |
| 13:30 |  | 이니셜 스크럼 |  |
|  |  | test 마무리 여부 확인 |  |
|  |  | 형키님 인수인계 | 팀 나가기, 팀 해체, 팀 완료 api 구현 요청, 프론트 엔드 작업자 파악 |
|  |  | 알람 모듈 작업 진행 |  |
|  |  | 후기 퇴고 |  |
| 17:00 |  | 저녁식사 |  |
|  |  | 운동 |  |
|  |  | 저녁 작업 |  |
| 23:00 | 24:00 | 독서 |  |
|  |  | 수면 |  |


## ToDo List
- [x] 버그 계열 먼저 작업 진행하기 
	- [x] 소개글 쪽 진행 마무리
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [x] 리팩토링 개시
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [x] 글 퇴고 1회 진행하기 
- [x] 공지 쓰기
## Issue - peer 
- [x] 관심 리스트 페이지 접속 시 500 에러 
- [x] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [ ] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [x] DnD Read Api  수정 : 204 수정(why? 아예 없을 때 새로 만들어야 하니까.);
- [x] 소켓 활용한 사용자 판단 event 제작 필요
- [x] 작성 글 퇴고
- [ ] 후기글 퇴고 필요
- [x] 사진 준비제출 완료

**Comment by HiHoi** [comment]
12 ~ 21

## TODO

- 소켓 연결
- 팀 역할 기능 변경

## 남은 일

- PWA 알림
- 알림
- 쇼케이스

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 공용 컴포넌트들 갈무리하기
- [ ] PR 리뷰
- [ ] PR 올리기
- [ ] custom breakpoints 오류 처리
- [ ] 마이페이지 토스트 메시지와 오류 처리 등 갈무리 

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정
- [ ] api 문서에 수정 사항 반영

**Comment by asroq1** [comment]
## TODO
- [ ] 쇼케이스 작성 폼 - 토스트 에디터 버그 수정
- [ ] 쇼케이스 작성 폼 - 이미지 base64 인코딩 해결

## 남은 할일
- [ ] API연동하기
- [ ] 에디터에 작성한 컨텐츠 유효성 검사

**Comment by wochae** [comment]
- [ ] com4 - 자원 제한 할당, 가상 아이피 할당 마무리
- [ ] 팀 게시판 - api 저장소 작성 마무리

**Comment by joonseong11** [comment]
- 외주 계약 관련 서류 작업중
