### ISSUE TITLE
2024-01-12-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#57]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 10:36 | 10:40 | 하루 준비 | 일정 정리, 작업 정리 |
| 10:40 |  | 후기 퇴고 |  |
| 12:00 | 13:00 | 점심 식사 |  |
| 13:30 |  | 이니셜 스크럼 |  |
|  |  | 알람 모듈 작업 진행 |  |
|  |  | test 마무리 여부 확인 | nginx 마무리, 서버 구동 확인, nhnCloud 폐쇄 |
|  |  | 알람 모듈 작업 진행 |  |
|  |  | 후기 퇴고 |  |
| 17:00 |  | 저녁식사 |  |
|  |  | 운동 |  |
| 23:00 | 24:00 | 독서 |  |
|  |  | 수면 |  |


## ToDo List
- [x] 버그 계열 먼저 작업 진행하기 
	- [x] 소개글 쪽 진행 마무리
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [x] 리팩토링 개시
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [x] 글 퇴고 1회 진행하기 
- [x] 공지 쓰기
## Issue - peer 
- [x] 관심 리스트 페이지 접속 시 500 에러 
- [x] 프로필 자기 소개글 이슈 픽스
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [ ] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [x] DnD Read Api  수정 : 204 수정(why? 아예 없을 때 새로 만들어야 하니까.);
- [x] 소켓 활용한 사용자 판단 event 제작 필요
- [x] 작성 글 퇴고
- [ ] 후기글 퇴고 필요
- [x] 사진 준비제출 완료

**Comment by joonseong11** [comment]
외주
- [ ] 견적서 정비완료 (검토중)
- [ ] 과업지시서 정비완료 (검토완료)
- [ ] 개발 계약서 작성완료 (검토완료)
- [ ] 프리랜서 계약서 작성완료 (검토중)
개발
- [ ] 모집글 개선사항 반영 (이미지 미업로드시 경고문구, 역할 제거 고장 등)
- [ ] 반영된 어드민 access token api 적용해보기
- [ ] 어드민 공지 부문 작업 (리스트, 작성, 수정)
기타
- [ ] 미용실 커트

**Comment by sinryuji** [comment]
- [ ] 팀 나가기
- [ ] 팀 해산사기
- [ ] 팀 완료하기
- [ ] 팀 역할 수정

**Comment by HiHoi** [comment]
13~19

- [ ] 팀 해산 프로세스 API 설계
- [ ] 팀 설정 페이지 변경점 진행
- [ ] 팀 리스트 변경점 진행

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 공용 컴포넌트들 갈무리하기
- [ ] 마이페이지 토스트 메시지와 오류 처리 등 갈무리 
- [ ] 마이페이지 API 논의 - 내 작업물, 스킬 등등
- [ ] 히치하이킹 백엔드 연결 

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정
- [ ] api 문서에 수정 사항 반영

**Comment by asroq1** [comment]
## TODO
 팀 해산 프로세스 API 설계
- [ ] 쇼케이스 폼 api 연동
- [ ] 쇼케이스 폼 에디터 유효성

## 남은 일들
- [ ] 쇼케이스 디테일 페이지 구현

**Comment by weejihye** [comment]
- [ ] toast editor 관련 마무리
- [ ] 팀설정 관련 hotfix
- [ ] 쇼케이스 구현

**Comment by wochae** [comment]
- [ ] 팀 게시판 api 저장소 의논하기
- [ ] 테스트 서버 설명하기 ( 클러스터 도착 후 설명 가능 )
- [ ] 저녁 약속 18:30

**Comment by hyeon81** [comment]
- [ ] 트센
- [ ] 버그 수정 (https://github.com/peer-42seoul/Peer-Frontend/issues/477)
- [ ] 모집글 ssr로 전환
- [ ] 모집글 디자인 다듬기
- [ ] 시간이 나면 dnd 레이아웃 수정 (반응형에 따라 레이아웃이 깨짐)
