### ISSUE TITLE
2024-01-15-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#58]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**                    | **내용**                                      |
|:------------:|:------------:| --------------------------- | --------------------------------------------- |
|    09:30     |    10:00     | 아침 식사                   |                                               |
|    10:00     |    11:00     | 일정 정리 및 고민 사항 정리 | 일정, 런칭 준비 관련                          |
|    11:00     |    11:30     | 나갈 준비                   |                                               |
|    11:30     |    13:00     | 이동 시간                   |                                               |
|    13:00     |    13:30     | 작업 준비                   |                                               |
|    13:30     |              | 이니셜 스크럼               |                                               |
|              |              | 작업                        | 코드 리뷰 요청, 백엔드 밋업, 프론트 엔드 밋업 |
|              |              | 리더스 회의                 | 런칭 준비 사항 정리, 역할 분배 준비           |
|              |              | 작업                        |                                               |
|              |              | 저녁 식사                   |                                               |
|              |              | 작업                        |                                               |
|              |              | 귀가                        |                                               |
|              |              | 독서                        |                                               |
|              |              | 수면                             |                                               |



## ToDo List
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [ ] 히나님 논의한 API 구현
	- [ ] 스킬 api
	- [ ] 나의 작업물 api 
## Issue - peer 
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [ ] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [ ] 스킬 API 구현 2개 
- [ ] 내 작업물 API 구현 3개

**Comment by HiHoi** [comment]
# 일정

| **시작 시간** | **종료 시간** | **제목** | **내용** |
|12:00|12:30|작업 준비|자리 셋팅 및 할일 정리|
|12:30|13:30|PR 집중 정리|주말 내 밀린 PR 확인 및 코멘트 확인|
|13:30|14:00|이니셜 스크럼|할일 정리 및 보고|
|14:00|15:00|리더회의|이번주 일정 정리 및 해야할 일 정리|
|15:00|17:00|작업|열심히 코딩|
|17:00|18:00|저녁식사|충전 중|
|18:00|21:00|작업 및 학습|피어 작업 및 개인 학습|

# TODO

- [ ] 소켓 연결 이슈 확인
- [ ] 알림 작업 진행 확인 후 작업
- [ ] 팀 설정 페이지에서 종료 프로세스: api 연결 및 팀원 모집 전이면 비활성화, DTO 수정
- [ ] 쇼케이스 작업: DB에 목업 넣고 수정할 부분 체크

**Comment by wochae** [comment]
- [ ] 팀 게시판 생성
- [ ] 특정 게시판 글 작성 ( 기존 코드에서 리팩토링 or 일반 게시글 작성 )
- [ ] api 약식 최신화 ( 작업 참고 용 )

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 게시판 페이지 구현

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현 ☑️
- 팀 게시판 api 논의, 연결 ☑️
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 
- 팀 게시판 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by asroq1** [comment]
## TODO
- [ ] 쇼케이스 작성폼 api 연결
## 남은 할일
- [ ] 쇼케이스 디테일 뷰 구현
- [ ] 쇼케이스 스타일

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 공용 컴포넌트들 갈무리하기
- [ ] 히치하이킹 백엔드 연결 
- [ ] 개인정보 설정 페이지 디자인
- [ ] 내 작업물 변경된 UI 적용
- [ ] 공용 PostCard 히치하이킹용 카드로 재변경

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정
- [ ] api 문서에 수정 사항 반영

**Comment by joonseong11** [comment]
- [ ]

**Comment by sinryuji** [comment]
- [ ] 팀 나가기
- [ ] 팀 해산사기
- [ ] 팀 완료하기
- [ ] 팀 역할 수정
