### ISSUE TITLE
2024-01-16-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#59]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**                   | **내용**                                             |
|:------------:|:------------:| -------------------------- | ---------------------------------------------------- |
|    07:00     |    08:00     | 아침 식사 준비 & 아침 식사 |                                                      |
|    08:00     |    08:30     | 휴식                       |                                                      |
|    08:30     |    08:50     | 일정 정리                  |                                                      |
|    09:00     |              | 작업                       | 피그마 와이어 프레임 제작, 비밀번호 암호화 전략 구상 |
|    11:00     |    11:30     | 나갈 준비                  |                                                      |
|    11:30     |    13:00     | 이동                       |                                                      |
|    13:00     |    13:30     | 클러스터 도착 및 미팅 준비 |                                                      |
|    13:30     |    15:30     | 전체 밋업 및 이니셜 스크럼 |                                                      |
|              |              | 작업                           |                                                      |




## ToDo List
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [ ] 히나님 논의한 API 구현
	- [ ] 스킬 api
	- [ ] 나의 작업물 api 
- [ ] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [ ] 전략 확정 
	- [ ] API 수정 
	- [ ] 테스트
- [ ] FIgma about 페이지 와이어 프레임 제작 
	- [ ] peer about 페이지 
	- [ ] 동료학습의 철학 
	- [ ] 개발 백서 모음 페이지 
	- [ ] 운영 규정
## Issue - peer 
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [ ] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [ ] 스킬 API 구현 2개 
- [ ] 내 작업물 API 구현 3개 
### Issue - 외주 (2/8)
- [ ] 계약서 작성하여 서명 만들어 놓기 
- [ ] 작업 일정 및 작업 단계 확정
- [ ]  작업 진행하기
### Issue - Self Study (~ 4/1)
- [ ] Java 보강
	- [ ] 인강 듣기 : 자바 ORM 표준 JPA 프로그래밍 - 기본편 
	- [ ] 인강 듣기 : 쉽게 배우는 자바 입문 과정
- [ ] Spring Boot 정리
	- [ ] Spring Boot Docs 스터디 
	- [ ] 인강 듣기 : Spring Boot 강의 듣기
- [ ] CS 마무리 및 복습 시작 
	- [ ] 책 복습하기 
- [ ] 알고리즘 문제 풀기
- [ ] 인강 듣기 : 개발자 영어

**Comment by HiHoi** [comment]
# 일정

| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|12:00|12:30|작업 준비|자리 셋팅 및 할일 정리|
|12:30|13:30|회의 준비|회의록 생성 및 할 말들 정리|
|13:30|14:00|이니셜 스크럼|할일 정리 및 보고|
|14:00|15:00|전체 회의|전체 회의 진행|
|15:00|17:00|작업|열심히 코딩|
|17:00|18:00|저녁식사|충전 중|
|18:00|21:00|작업 및 학습|피어 작업 및 개인 학습|

# TODO

- [ ] 알림 작업
- [ ] 팀 설정 페이지에서 종료 프로세스: api 연결 및 팀원 모집 전이면 비활성화, DTO 수정
- [ ] 쇼케이스 작업: DB에 목업 넣고 수정할 부분 체크

**Comment by sinryuji** [comment]
- [ ] 비밀번호 변경 리팩토링

**Comment by joonseong11** [comment]
해야할 일
- 어드민 공지 배너 태그 (화요일까지)
- 어드민 신고 (목요일까지)
- 어드민 알람 (?)

오늘 할 일
- [ ] 어드민 공지 작성 및 수정에 리액트훅폼 적용
- [ ] 배너 리스트
- [ ] 배너 작성
- [ ] 배너 수정
- [ ] 태그 리스트

**Comment by KRimwoo** [comment]
- [ ] 상대방 프로필보기 api 요청하기.. 연결만 하면 됨!
- [ ] minishell!

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 숨고 커피챗 (오후 3시)
- [ ] 공용 컴포넌트들 갈무리하기
- [ ] 히치하이킹 백엔드 연결 
- [ ] 개인정보 설정 페이지 디자인
- [ ] 내 작업물 변경된 UI 적용
- [ ] 공용 PostCard 히치하이킹용 카드로 재변경

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 게시판 페이지 구현
- [ ] 팀 게시판 api 연결

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현 ☑️
- 팀 게시판 api 논의, 연결 ☑️
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 
- 팀 게시판 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by hyeon81** [comment]
- [ ] dnd 레이아웃 오류 수정
- [ ] 좋아요 api 분리되길 기다리기
- [ ] 버그 픽스 https://github.com/peer-42seoul/Peer-Frontend/issues/477
- [ ] 기타 수정할 부분 찾아서 하기

**Comment by wochae** [comment]
- [ ] 팀 게시판 삭제 구현
- [ ] 팀 api 바인딩

**Comment by weejihye** [comment]
- [ ] 쇼케이스
- [ ] 좋아요 API 분리

**Comment by asroq1** [comment]
## TODO
- [ ] 쇼케이스 작성 폼 - api 연동
- [ ] 쇼케이스 작성 폼 - 링크 폼 수정

## 남은 할일
- [ ] 쇼케이스 디테일 페이지 구현
- [ ] 쇼케이스 디테일 페이지 토스트 뷰어 삽입
