### ISSUE TITLE
2024-01-17-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#60]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
TODO List (작업중)

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 06:00 | 08:15 | 작업 | 민감 정보 암호화 전략 고민(RSA, JWT), 회의 내용 정리 및 공지 작성, TODO List 업데이트 해두기 |
|  |  | 아침 정리 및 식사 |  |
|  |  | 작업 |  |
|  |  | 점심 준비 및 식사 |  |
|  |  | 휴식 |  |
|  |  | 이니셜 스크럼 |  |
|  |  | 작업 |  |
|  |  | 저녁 준비 및 식사 |  |
|  |  | 산책 |  |
|  |  | 작업 |  |
|  |  | 취침 |  |




## ToDo List
- [ ] 전체 일정 정리 및 TODO List 로 만들어 놓기
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [ ] 히나님 논의한 API 구현
	- [ ] 스킬 api
	- [ ] 나의 작업물 api 
- [ ] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [ ] 전략 확정 
	- [ ] API 수정 
	- [ ] 테스트
- [ ] 우리킴님 논의한 API 구현 
	- [ ] 상대방 프로필 보기
## Issue - peer 
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [ ] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [ ] 스킬 API 구현 2개 
- [ ] 내 작업물 API 구현 3개

**Comment by sinryuji** [comment]
- [ ] 메인 서버 세팅

**Comment by asroq1** [comment]
## TODO
- [ ] 링크 폼 정규식 넣기
- [ ] Circular 공용 컴포넌트 생성
- [ ] 밀린 코드리뷰 하기

**Comment by HiHoi** [comment]
# TODO

- about 페이지 api 작업
- 팀설정 페이지 종료 프로세스 연동: 현재 정상 완료는 문제 없음
- 쇼케이스 작성 페이지 테스트
- 쇼케이스 테스트 후 수정할 부분 수정

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 히치하이킹 백엔드 연결 
- [ ] 개인정보 설정 페이지 디자인
- [ ] 공용 PostCard 히치하이킹용 카드로 재변경

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 게시판 페이지 구현
  - 게시판에서 추가된 기능 (게시판 관리 / 여러 게시판) 페이지 구현 완료
  - api 연결해보면서 놓친 부분 보완할 예정..
- [ ] 팀 게시판 api 마저 연결
  - 게시판 생성 / 삭제 / 게시판 목록 조회 까지 완료함

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현 ✅️
- 팀 게시판 api 논의, 연결 ☑️
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 
- 팀 게시판 위젯 구현
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by joonseong11** [comment]
# TODO

- [ ] 어드민 공지 작성 멀티파트 에러 해결
- [ ] 어드민 태그 리스트 작성 수정
- [ ] 어드민 배너 리스트 작업

-----
- [ ] toast 에디터 원치않은 오토포커싱 문제 해결 필요 (리액트훅폼아니더라도 발생)

**Comment by wochae** [comment]
- [ ] 팀 게시판 반환 타입, 상태코드 리팩토링
- [ ] 공지 한 입만
- [ ] 엔진엑스 컨테이너화
