### ISSUE TITLE
2024-01-18-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#61]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 08:00 | 10:30 | 휴식 |  |
| 10:30 | 10:40 | 하루 일정 정리 |  |
| 10:40 |  | 작업 | 나의 작업물 작업하기, API 작성하기 |
|  |  | 점심 준비 및 식사 |  |
|  |  | 휴식 |  |
| 13:30 |  | 이니셜 스크럼 |  |
|  |  | 작업 |  |
|  |  | 저녁 준비 및 식사 |  |
|  |  | 산책 |  |
|  |  | 작업 |  |
|  |  | 취침 |  |

## ToDo List
- [ ] 전체 일정 정리 및 TODO List 로 만들어 놓기
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
- [x] 히나님 논의한 API 구현
	- [x] 스킬 api
	- [ ] 나의 작업물 api 
- [x] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [x] 전략 확정 
	- [ ] 관련 멤버에게 전달 및 인수인계
	- [ ] API 수정 
	- [ ] 테스트
- [ ] 우리킴님 논의한 API 구현 
	- [ ] 상대방 프로필 보기
## Issue - peer 
- [ ] 회원가입 탈퇴 기능 추가 구현(우채?)
- [ ] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [ ] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] (가능?) 쇼케이스 기능 구현(제이위)
- [x] 스킬 API 구현 2개 
- [ ] 내 작업물 API 구현 3개

**Comment by HiHoi** [comment]
## TODO

- [ ] about 페이지 작업
- [ ] 쇼케이스 작업
- [ ] DTO 수정

**Comment by asroq1** [comment]
##TODO
- [ ] 404, 500 페이지 구현
- [ ] 디테일 페이지 구현

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 히치하이킹 api 빠진 정보 논의
- [ ] 개인정보 설정 페이지 디자인
- [ ] 관심리스트 메인 로직 수정

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정

**Comment by joonseong11** [comment]
# TODO

- [x] 어드민 공지 작성 멀티파트 에러 해결
- [x] 어드민 태그 리스트 작성 수정
- [ ] 어드민 배너 리스트 작업
- [x] pr 확인
-----
- [ ] toast 에디터 원치않은 오토포커싱 문제 해결 필요 (리액트훅폼아니더라도 발생)

- [ ] 공지 배너용 리스트, 작성, 수정 공통컴포넌트화
- [ ] 4시 숨고 커피챗
- [ ] 태그 리스트

**Comment by wochae** [comment]
- [ ] 게시판 유효성 검사
- [ ] pr확인
- [ ]

**Comment by sinryuji** [comment]
- [ ] 메인서버 세팅
- [ ] 사용자 추적 모듈 추가 개발(팀 해산하기, 팀 완료하기)
