### ISSUE TITLE
2024-01-22-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#63]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by HiHoi** [comment]
## TODO

- [ ] 쇼케이스 PC 버전 픽스
- [ ] about 페이지 백엔드 연동 작업
- [ ] PWA 아이콘 교체
- [ ] 배너 이미지 삽입
- [ ] 메인 화면에 쇼케이스 로직 구상

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 프로필 스킬 수정 구현 - 유효성 검사 추가
- [ ] 개인정보 설정 페이지 디자인
- [ ] 내 작업물 UI 변경 및 백엔드 연결

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정

**Comment by yoouyeon** [comment]
### TODO

- [ ] 공지사항 위젯
- [ ] 게시판 위젯

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현 ✅️
- 팀 게시판 api 논의, 연결 ☑️
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 ☑️
- 팀 게시판 위젯 구현 ☑️
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 07:00 | 09:30 | 작업 | 민감 정보 JWT 암호화 마무리 |
| 09:00 | 10:30 | 아침 정리 및 식사 |  |
| 10:30 | 13:00 | 휴식 | 추가 잠자기.. |
| 13:10 | 13:30 | 일정 정리 |  |
| 13:30 |  | 이니셜 스크럼 |  |
|  |  | 작업 | 공지 쓰기, 진행 사항 정리하기, 민감 정보 암호화 문서 작업 마무리 짓기, 알림 작업 |
|  |  | 저녁 준비 및 식사 |  |
|  |  | 산책 |  |
|  |  | 독서 |  |
|  |  | 취침 |  |




## ToDo List
- [x] 전체 일정 정리 및 TODO List 로 만들어 놓기
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
	- [ ] 알림 키워드 지정에 따른 알림 키워드 전달 작업 만들기
		- [ ] 스케쥴링
		- [ ] 백그라운드 전달 기능 구현
- [x] 히나님 논의한 API 구현
	- [x] 스킬 api
	- [x] 나의 작업물 api 
- [x] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [x] 전략 확정 
	- [x] API 수정 
	- [x] 테스트
	- [ ] 문서화 및 프론트엔드 개발자 사용 가능한 가이드 작성
- [x] 우리킴님 논의한 API 구현 
	- [x] 상대방 프로필 보기
## Issue - peer 
- [x] 회원가입 탈퇴 기능 추가 구현
- [x] team 종료 로직 구현 [참고 링크](https://docs.google.com/spreadsheets/d/1Dq1gftt09NmDohKkpLfPB9RuKYkbsOXc_iIj7t4yZiM/edit?usp=sharing)
	- [x] 형키님 전달
- [ ] 알람 스프링 모듈 구현
- [ ] 알람 nest 모듈 구현
- [ ] 쇼케이스 기능 구현(제이위)
- [x] 스킬 API 구현 2개 
- [x] 내 작업물 API 구현 3개 
- [x] 이후 작업해야할 일 
	- [x] 프로필 강화(프로필 스킬 태그 보여주기, 피어 레벨 등... )

**Comment by asroq1** [comment]
## TODO
 - [ ] 쇼케이스 수정폼
 - [ ] 쇼케이스 댓글
 
## 남은 할일
- [ ] 스타일 적용

**Comment by sinryuji** [comment]
- [ ] 메인서버 CI/CD

**Comment by joonseong11** [comment]
- 모집글에서 제시된 qa

**Comment by wochae** [comment]
- [ ] 팀 게시판 공지사항 바인딩
- [ ] 더미 데이터 스크립트

**Comment by weejihye** [comment]
- [ ] showcase 추가 api 구현
- [ ] recruit 조회시 응답 필드 이름 수정
- [ ] 그외 핫픽스
