### ISSUE TITLE
2024-01-23-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#64]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 08:00 | 09:07 | 책 스캔 | 학습할 책 스캔 테스팅 |
| 09:07 | 09:20 | 일정 정리 | 금일 진행 사항 체크, 밑 준비, 일정 확인 |
|  |  | 이동 |  |
| 10:00 | 10:40 | 미용실 |  |
|  |  | 이동 |  |
|  |  | 점식식사 |  |
|  |  | 이동 |  |
|  |  | 작업 | 히나님 더미 데이터 넣어 드리기 |
| 14:00 |  | 전체 회의 |  |
|  |  | 이니셜 스크럼 |  |
|  |  | 도서 대출 |  |
|  |  | 작업 | 문서화(암호화 전략, signUp 변경 점) |
|  |  | 저녁식사 |  |
|  |  |  |  |




## ToDo List
- [x] 전체 일정 정리 및 TODO List 로 만들어 놓기
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
	- [ ] 알림 키워드 지정에 따른 알림 키워드 전달 작업 만들기
		- [ ] 알림 키워드 작업 API 지정
		- [ ] 스케쥴링
		- [ ] 백그라운드 전달 기능 구현
- [x] 히나님 논의한 API 구현
	- [x] 스킬 api
	- [x] 나의 작업물 api 
- [x] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [x] 전략 확정 
	- [x] API 수정 
	- [x] 테스트
	- [ ] 문서화 및 프론트엔드 개발자 사용 가능한 가이드 작성
- [x] 우리킴님 논의한 API 구현 
	- [x] 상대방 프로필 보기
- [ ] 주전 SignUp 문서화 수정하기

**Comment by HiHoi** [comment]
## TODO

- [ ] CI CD 테스트 서버 쪽 문제 해결: 아마 환경변수 문제 같음
- [ ] 소켓 최신화 PR
- [ ] about 페이지 작업
- [ ] 자잘한 에러 처리: 토스트 알림 적용

**Comment by wochae** [comment]
- [ ] 테스트 서버 보조
- [ ] 게시판 공지사항 마무리
- [ ]

**Comment by KRimwoo** [comment]
- [ ] 상대방 프로필보기에 작업물 추가

**Comment by hyeon81** [comment]
- [ ] Dnd pr 수정
- [ ] 헤더 추가 pr 올리기
- [ ] 트센

**Comment by asroq1** [comment]
### 오늘 할 일
- [ ] 팀페이지에서 쇼케이스 작성 완료
- [ ] 쇼케이스 수정 페이지 previewImage 이슈
- [ ] 쇼케이스 에디터 이미지 삽입 이슈 확인


### 남은 할일
- [ ] 스타일 적용

**Comment by joonseong11** [comment]
- [ ] 모집글에 토스트에디터 적용
- [ ] 어드민 공지 페이지네이션 첫 갱신 안되는 오류 고치기
- [ ] 어드민 공지 토스트 에디터 적용

**Comment by yoouyeon** [comment]
### TODO

- [ ] 공지사항 위젯 마무리

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현 ✅️
- 팀 게시판 api 논의, 연결 ☑️
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 ☑️
- 팀 게시판 위젯 구현 ☑️
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅
