### ISSUE TITLE
2024-01-24-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#65]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by HiHoi** [comment]
## TODO

- [ ] 베타 뱃지 피드백 반영: 색상 부분이나 플랫한 디자인으로의 변경 고려
- [ ] 알림 탭 부분: 디자인 변경 사항이나 라이트 모드일 때 디자인 체크
- [ ] 쇼케이스: 디테일 페이지 리다이렉션, 테스트 데이터 생성 후 연결이 잘 되는지 체크, 라이트 모드 디자인 체크
- [ ] 튜토리얼: 문서 정리
- [ ] about 페이지: 테스트 목업 넣고 체크

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 개인정보 설정 페이지 디자인(보안 작업 포함)
- [ ] 베스트 피어로그 팀 및 작성자 리스트업하기

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 06:00 | 08:00 | 북 스캔 | 가상 면접 사례로 배우는 대규모 시스템 설계 기초,<br>SQL, SQLD 비밀노트,<br>핵심 데이터 모델링<br>작업환경 세팅 및 기타 등등 |
| 08:00 | 09:00 | 문서 작업 | privateInfoWrapping 모듈 문서화 및 정리 |
| 09:00 | 09:30 | 아침식사 |  |
|  |  | 휴식 |  |
| 11:00 | 12:30 | 점심 식사 |  |
| 13:00 | 13:30 | 작업 전 준비 |  |
| 13:30 |  | 이니셜 스크림 |  |
|  |  | 작업 | COM1, COM3 포맷, 남은 작업들 진행 |
|  |  | 저녁 식사 준비 & 저녁 식사 |  |
|  |  | 정리 |  |
|  |  | 운동 |  |
|  |  | 독서 |  |
|  |  | 취침 |  |




## ToDo List
- [x] 전체 일정 정리 및 TODO List 로 만들어 놓기
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
	- [ ] 알림 키워드 지정에 따른 알림 키워드 전달 작업 만들기
		- [ ] 알림 키워드 작업 API 지정
		- [ ] 스케쥴링
		- [ ] 백그라운드 전달 기능 구현
- [x] 히나님 논의한 API 구현
	- [x] 스킬 api
	- [x] 나의 작업물 api 
- [x] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [x] 전략 확정 
	- [x] API 수정 
	- [x] 테스트
	- [x] 문서화 및 프론트엔드 개발자 사용 가능한 가이드 작성
- [x] 우리킴님 논의한 API 구현 
	- [x] 상대방 프로필 보기
- [x] 주전 SignUp 문서화 수정하기
- [ ] about 페이지 API 연동
- [ ] 상대방 프로필 보기 API 수정 
- [ ] COM1, COM3 포맷 및 영어로만 설정하기
- [x] 오늘 회의 내용 정리 및 공지

**Comment by yoouyeon** [comment]
### TODO

- [ ] 팀 게시판 api 연결중 발견된 버그 수정
- [ ] PR 리뷰 (DnD 업데이트 로직)
- [ ] 튜토리얼 문서화 마무리 (모집글 관련)
- [ ] 캘린더 위젯 디자인 / 모달 작업 마무리..

### 남은 할일
- 캘린더 위젯 디자인 적용 마무리 ☑️
- 캘린더 api 테스트
- 팀 공지사항 디자인 ✅
- 팀 게시판 페이지 구현 ✅️
- 팀 게시판 api 논의, 연결 ☑️
- 팀 게시판 디자인 ✅
- 팀 공지사항 위젯 구현 ✅️
- 팀 게시판 위젯 구현 ☑️
- ==
- toast와 모달 겹침 확인 (z-index 수정?)
- 모바일 네비게이션 배경색 컬러팔레트 확인하기 ✅

**Comment by wochae** [comment]
- [ ] 팀 게시판 api 연결 중 발견된 버그 수정 보조
- [ ] 태그 작업
- [ ] 더미 데이터 스크립트

**Comment by sinryuji** [comment]
- [ ] 메인서버 세팅
- [ ] 메인서버 CI/CD
