### ISSUE TITLE
2024-01-25-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#66]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today 
- [ ] about 페이지 연동 
	- [ ] 공지사항 API 만들기 및 연동 
	- [ ] ContactUs API  만들기 및 연동(이메일 전송 파트까지)
- [ ] 알림 모듈 작업하기
- [ ] 개발백서 피드백 전달하기

**Comment by HiHoi** [comment]
## TODO

- [ ] 알림 탭 부분: 디자인 변경 사항이나 라이트 모드일 때 디자인 체크
- [ ] 튜토리얼: 구현 모양 잡기

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 개인정보 설정 페이지 디자인(보안 작업 포함)
- [ ] jsonwebtoken 라이브러리 활용하여 보안 작업 하기
- [ ] 프로필 스킬 수정 버그픽스
- [ ] PR올린 페이지들 머지된 후 스타일 코드 분리하기

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정

**Comment by sinryuji** [comment]
- [ ] 메인서버 CI/CD

**Comment by asroq1** [comment]
## TODO

- [ ] CSS 적용하기
- [ ] 404, 500 애니메이션 페이지 적용하기

**Comment by wochae** [comment]
- [ ] 팀 게시판 QA
