### ISSUE TITLE
2024-01-26-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#67]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 09:30 | 10:00 | 아침 식사 |  |
| 10:00 |  | 일정 정리 |  |
|  |  | 작업 | 기타 작업 진행 |
|  |  | 점심 식사 |  |
|  |  | 휴식 |  |
| 13:30 |  | 이니셜 스크럼 |  |
|  |  | 작업 | 히나님 JWT 쪽 돕기, 내 작업 진행 |
|  |  | 저녁 식사 |  |
|  |  | 저녁 잔업 |  |
|  |  | 독서 |  |
|  |  | 취침 |  |

## ToDo List
- [x] 전체 일정 정리 및 TODO List 로 만들어 놓기
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 리팩토링 개시 ⭐️
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
	- [ ] 알림 키워드 지정에 따른 알림 키워드 전달 작업 만들기
		- [ ] 스케쥴링
		- [ ] 백그라운드 전달 기능 구현
- [x] 히나님 논의한 API 구현
	- [x] 스킬 api
	- [x] 나의 작업물 api 
- [x] 계정 관련 API 암호화 및 복호화 전략 세우기
	- [x] 전략 확정 
	- [x] API 수정 
	- [x] 테스트
	- [x] 문서화 및 프론트엔드 개발자 사용 가능한 가이드 작성
- [x] 우리킴님 논의한 API 구현 
	- [x] 상대방 프로필 보기

**Comment by sinryuji** [comment]
- [ ] 팀 해산하기 추적
- [ ] 팀 완료하기 추적

**Comment by asroq1** [comment]
- [ ] 쇼케이스 작성 페이지 - 스타일링
- [ ] 쇼케이스 수정 페이지 - 스타일링
- [ ] 팀페이지 내 쇼케이스 페이지 - 스타일링

**Comment by SaltySalt77** [comment]
### TODO
- [ ] 개인정보 설정 페이지 디자인(보안 작업 포함)
- [ ] 비밀번호 변경 데모 만들기
- [ ] jsonwebtoken 라이브러리 활용하여 보안 작업 하기
- [x] 프로필 스킬 수정 버그픽스
- [ ] PR올린 페이지들 머지된 후 스타일 코드 분리하기

### 남은 할일
- [ ] 회원가입 닉네임 최대 길이 조정
