### ISSUE TITLE
2024-01-29-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#68]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 09:30 | 10:20 | 아침 식사 | 아침 식사 & 휴식 |
| 10:20 |  | 하루 일과 정리 | 금일 할 일 정리 & 일정 문서 작성 |
| 10:30 |  | 아침 작업 | dnd sub calendar 상태 파악 및 핫픽스 진행 |
|  |  | 점심 식사 | 점심 식사 & 휴식 |
| 13:30 |  | 이니셜 스크럼 | 현재 진행상황 파악 & 내일 전체 회의 준비 |
|  |  | 오후 작업 | dnd sub 핫픽스 , 알람 모듈 작업 |
|  |  | 저녁 식사 |  |
|  |  |  |  |
|  |  |  |  |

**Comment by sinryuji** [comment]
- [ ] 신고 체계 프로세스 구상

**Comment by wochae** [comment]
- [ ] 외주 사전 회의 ~ 21:00

--
피어

팀 게시판 QA

**Comment by asroq1** [comment]
### TODO
- [ ] Tag 추가 관련 사항 리서치
- [ ] 404 페이지 트랜스파일링
- [ ] 404 페이지 애니메이션 적용

**Comment by SaltySalt77** [comment]
### Todo
- [ ] 보안 작업 관련 컴포넌트 인수인계 문서 작성
- [ ] 로그인 페이지 보안 작업 처리
- [ ] 비밀번호 변경 페이지 모바일 디자인 처리

**Comment by yoouyeon** [comment]
- [ ] 캘린더 위젯 마무리 후 PR 올리기
- [ ] 팀 공지사항 / 팀 게시판 api 연결 작업 계속...

**Comment by HiHoi** [comment]
ToDo

- 베타 배찌 완성
- 쇼케이스 종료
- 팀 설정 부분 완료

**Comment by weejihye** [comment]
- [ ] ~18:00 트샌
- [ ] toast Editor 이미지 저장 작업
