### ISSUE TITLE
2024-01-30-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#69]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**          | **내용**                         |
|:------------:|:------------:| ----------------- | -------------------------------- |
|    06:00     |    07:10     | 필요한 사항 정리  | 런칭전 준비 사항 정리, 일정 정리 |
|    07:10     |              | 작업 진행         |                                  |
|              |              | 아침 식사         |                                  |
|    09:30     |    11:00     | 나갈 준비 및 이동 |                                  |
|    11:00     | 12:00             | 점심 식사         |                                  |
|              |              | 작업 진행         |                                  |
|    14:00     |              | 전체 회의         |                                  |
|              |              | 이니셜 스크럼     |                                  |
|              |              | 작업 진행         |                                  |
|              |              | 저녁 식사         |                                  |




## ToDo List
- [ ] 런칭 시 필요한 사항들 전체 정리하기 
- [ ] 알림 스프링 모듈 파트 진행하기
	- [x] 전체 명칭 리펙토링 
	- [x] 엔티티 파악
	- [x] controller 파악 
	- [x] service 파악
	- [x] 구현 정도 파악 
	- [ ] 알람 적용하기 
		- [ ] 각 api 들마다 알람 생성 집어넣기 
		- [ ] 알람 메인 컨트롤러 만들기
			- [ ] 생성 로직
			- [ ] 삭제 로직
		- [ ] 오프라인 상태일 때, 구독 시 상황 만들기 
		- [ ] 정기 스케쥴러 만들기
		- [ ] 오프라인 일 때, 정기 스케쥴링 -> NestJS 전송기 만들기 
	- [ ] application gradle 파일 설정 수정 
	- [ ] NestJS 구축
	- [ ] 알림 키워드 지정에 따른 알림 키워드 전달 작업 만들기
		- [ ] 스케쥴링
		- [ ] 백그라운드 전달 기능 구현
- [ ] 메시지 api 수정하기
- [ ] 알림 적용 시키기
	- [ ] 공지
	- [ ] 어드민 
	- [ ] 쪽지
	- [ ] 팀

**Comment by sinryuji** [comment]
- [ ] DB 백업 작업
- [ ] 신고 체계 프로세스 구상
- [ ] 메인 버전 배포 전략 문서화
- [ ] DB 백업 전략 문서화

**Comment by KRimwoo** [comment]
- [ ] authStore에 userId 추가하기, oauth login 오류 파악
- [ ] 상대방 프로필 팝업 본인 계정은 안뜨게 하기
- [ ] 상대방 프로필 작업물보기 pr올리기

**Comment by wochae** [comment]
-[] 공지게시글 리스트 오류 해결

**Comment by asroq1** [comment]
- [ ] 인수인계 문서 작성
- [ ] 태그 리스트 작성 및 검토

**Comment by hyeon81** [comment]
- [ ] DnD 생성/업데이트 로직 변경: key의 타입 바꾸기
- [ ] 네비게이션바 디자인 수정, 헤더 타이틀 설정 바꾸기
- 이슈 수정
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/477
- [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/459
- [ ] 검정색 테두리 지우기
- [ ] 좋아요 API 교체하기

**Comment by SaltySalt77** [comment]
### Todo
- [ ] 보안 작업 관련 컴포넌트 인수인계 문서 작성
- [ ] 비밀번호 변경 페이지 모바일 디자인 처리

**Comment by joonseong11** [comment]
- [ ] 모집글쓰기 작성완료에 로딩 처리 추가
- [ ] 모집글쓰기에 라이트모드시에 깨지는 디자인 수정
- [ ]

**Comment by HiHoi** [comment]
## TODO

- 튜토리얼 내용 정리 이후 나눠서 구현
- 쇼케이스 QA
- 팀설정 QA
- 메인 로직 QA
- 데이터 없을 때 보여줄 이미지 추가 작업

## 남은 일
