### ISSUE TITLE
2024-01-31-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#70]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목** | **내용** |
| :--: | :--: | ---- | ---- |
| 07:00 | 09:30 | 작업 | 민감 정보 JWT 암호화 마무리 |
| 09:00 | 10:30 | 아침 정리 및 식사 |  |
| 10:30 | 13:00 | 휴식 | 추가 잠자기.. |
| 13:10 | 13:30 | 일정 정리 |  |
| 13:30 |  | 이니셜 스크럼 |  |
|  |  | 작업 | 공지 쓰기, 진행 사항 정리하기, 민감 정보 암호화 문서 작업 마무리 짓기, 알림 작업 |
|  |  | 저녁 준비 및 식사 |  |
|  |  | 산책 |  |
|  |  | 독서 |  |
|  |  | 취침 |  |

**Comment by HiHoi** [comment]
## TODO

- 소켓 연결 확인
- CI/CD 구축
- PWA 버그 수정

**Comment by wochae** [comment]
- 외주 회의로 스크럼 참여 불가
- 팀 게시판 관련 문제 항시 대기

**Comment by sinryuji** [comment]
- [ ] nginx 접속량 제한 작업
- [ ] 메인 버전 릴리즈 문서화
- [ ] 디비 백업 문서화

**Comment by SaltySalt77** [comment]
### Todo
- [ ] pr 올리기
- [ ] 관심리스트 endpoint 변경 건 처리
- [ ] 비밀번호 모바일
- [ ] next/Image 컴포넌트 테스트

**Comment by yoouyeon** [comment]
- [ ] 팀 게시판 api 연결하는중 (연결과 함께 잔버그 계속 수정중입니다)
- [ ] 튜토리얼용 공통 모달 만들기

**Comment by asroq1** [comment]
## TODO
- [ ] 쇼케이스 댓글 기능 추가 
- [ ] 쇼케이스 뷰 페이지 옆에 상호작용 버튼 추가

**Comment by joonseong11** [comment]
- [ ] 사업자용 공인인증서 발급 완료
- [ ] 발주사 세금계산서 처리
- [ ] 부가가치세 신고 알아보기
- [ ] 어드민 공지 부문 정리 후 pull request
