### ISSUE TITLE
2024-02-01-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#71]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by asroq1** [comment]
## TODO
- [ ] 쇼케이스 댓글 기능 추가 
- [ ] 쇼케이스 뷰 페이지 옆에 상호작용 버튼 추가

**Comment by sinryuji** [comment]
- [ ]  피어 메인 버전 배포 문서화
- [ ]  피어 DB 백업 문서화

**Comment by SaltySalt77** [comment]
### Todo
- [ ] 쇼케이스 데이터 이전 리스트업 및 작업분배
- [ ] 모집글 작성 로직 파악
- [ ] 모집글 React-hook-form 연결

**Comment by hyeon81** [comment]
* 수정
- [ ] 헤더 최적화
- [ ] 네비게이션 색 수정
- [ ] 좋아요 GET API 추가
- [ ]  select 디자인 수정
- [ ] 본인이 만든 모집글은 지원못하도록 하기

* pr 올리기
 - [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/477
 - [ ] https://github.com/peer-42seoul/Peer-Frontend/issues/459
 - [ ] 메인 페이지 검정색 테두리 지우기

**Comment by joonseong11** [comment]
- [ ] 어드민 공지 관리 페이지에서 DateTimePicker, useForm 반영해서 글작성/수정 기능 반영 필요 (useForm 잘쓰시는 분...)
- [ ] 공지 관리 페이지 정리되면 활용해서 배너 관리페이지 작업 후 pr
