### ISSUE TITLE
2024-02-02-TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/management-team-todo#72]
# 투두리스트 작성하는 법
### 참고사항 본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)
---
### ToDo List 작성 예시 : 마크다운 표 작성 방식 참고할 것! 귀찮으면 긁어서 사용하시면 됩니다~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |
// 요걸 잘 활용해서 내용을 적으면 아래처럼 표시가 됩니다 ~
```
| **시작 시간** | **종료 시간** | **제목** | **내용** |
|:---:|:---:|:---|:---|
|09:00|13:00|제목 작성|내용작성 |

**Comment by SaltySalt77** [comment]
### Todo
- [ ] 모집글 리액트 훅 폼 연결하기 (이미지, 역할, 인터뷰 남음)
- [ ] 모집글 디자인 (이미지, 인터뷰, 인터뷰 폼 등등)

**Comment by hyeon81** [comment]
- [ ] pr 올리기
- [ ] 좋아요 오류 수정 
- [ ] 모바일 네비게이션바 디자인 수정
- [ ] 모바일 헤더 최적화
- [ ] 모집글, 메인페이지 QA 및 버그 픽스

**Comment by sinryuji** [comment]
- [ ] OAuth 고치기

**Comment by asroq1** [comment]
## TODO
- [ ] 쇼케이스 댓글 스타일 정리하기
- [ ] 쇼케이스 상호작용 버튼들 접근권한 수정

**Comment by Paul2021-R** [comment]
# Today Note

| **시작시간** | **종료시간** | **제목**      | **내용**                              |
|:------------:|:------------:| ------------- | ------------------------------------- |
|    11:10     |              | 작업 준비     | 금일 일정 정리 및 작업 준비           |
|              |              | 점심식사      |                                       |
|              |              | 휴식          |                                       |
|              |              | 이니셜 스크럼 |                                       |
|              |              | 작업          | 1. dev 브랜치 현재 entity들 전체 점검<br>2. 메인 서버 CICD 상태 점검 <br>3. 프론트엔드 CICD 점검 |
|              |              |               |                                       |

**Comment by HiHoi** [comment]
## TODO

1. 소켓 재연결
2. 튜토리얼 내용 마무리
3. 메인 서버 CI CD 재검토: 환경변수 설정만 하면 될 수 있게
4. 만든 부분 QA
5. 베터 뱃지: 위치 변경
